// Code generated by generator/blocks/main.go; DO NOT EDIT.
package block

import "github.com/Tnze/go-mc/level/block/states"

var (
	SnowyProperty = states.NewPropertyBoolean("snowy")

	StageProperty = states.NewPropertyInteger("stage", 0, 1)

	Age4Property = states.NewPropertyInteger("age", 0, 4)

	HangingProperty = states.NewPropertyBoolean("hanging")

	WaterloggedProperty = states.NewPropertyBoolean("waterlogged")

	LevelProperty = states.NewPropertyInteger("level", 0, 15)

	DistanceProperty = states.NewPropertyInteger("distance", 1, 7)

	PersistentProperty = states.NewPropertyBoolean("persistent")

	TriggeredProperty = states.NewPropertyBoolean("triggered")

	NoteProperty = states.NewPropertyInteger("note", 0, 24)

	PoweredProperty = states.NewPropertyBoolean("powered")

	OccupiedProperty = states.NewPropertyBoolean("occupied")

	ExtendedProperty = states.NewPropertyBoolean("extended")

	ShortProperty = states.NewPropertyBoolean("short")

	UnstableProperty = states.NewPropertyBoolean("unstable")

	Age15Property = states.NewPropertyInteger("age", 0, 15)

	EastProperty = states.NewPropertyBoolean("east")

	NorthProperty = states.NewPropertyBoolean("north")

	SouthProperty = states.NewPropertyBoolean("south")

	UpProperty = states.NewPropertyBoolean("up")

	WestProperty = states.NewPropertyBoolean("west")

	PowerProperty = states.NewPropertyInteger("power", 0, 15)

	Age7Property = states.NewPropertyInteger("age", 0, 7)

	MoistureProperty = states.NewPropertyInteger("moisture", 0, 7)

	LitProperty = states.NewPropertyBoolean("lit")

	RotationProperty = states.NewPropertyInteger("rotation", 0, 15)

	OpenProperty = states.NewPropertyBoolean("open")

	LayersProperty = states.NewPropertyInteger("layers", 1, 8)

	HasRecordProperty = states.NewPropertyBoolean("has_record")

	BitesProperty = states.NewPropertyInteger("bites", 0, 6)

	DelayProperty = states.NewPropertyInteger("delay", 1, 4)

	LockedProperty = states.NewPropertyBoolean("locked")

	DownProperty = states.NewPropertyBoolean("down")

	InWallProperty = states.NewPropertyBoolean("in_wall")

	Age3Property = states.NewPropertyInteger("age", 0, 3)

	HasBottle0Property = states.NewPropertyBoolean("has_bottle_0")

	HasBottle1Property = states.NewPropertyBoolean("has_bottle_1")

	HasBottle2Property = states.NewPropertyBoolean("has_bottle_2")

	EyeProperty = states.NewPropertyBoolean("eye")

	Age2Property = states.NewPropertyInteger("age", 0, 2)

	AttachedProperty = states.NewPropertyBoolean("attached")

	DisarmedProperty = states.NewPropertyBoolean("disarmed")

	ConditionalProperty = states.NewPropertyBoolean("conditional")

	InvertedProperty = states.NewPropertyBoolean("inverted")

	EnabledProperty = states.NewPropertyBoolean("enabled")

	Age5Property = states.NewPropertyInteger("age", 0, 5)

	Age25Property = states.NewPropertyInteger("age", 0, 25)

	EggsProperty = states.NewPropertyInteger("eggs", 1, 4)

	HatchProperty = states.NewPropertyInteger("hatch", 0, 2)

	PicklesProperty = states.NewPropertyInteger("pickles", 1, 4)

	Age1Property = states.NewPropertyInteger("age", 0, 1)

	DragProperty = states.NewPropertyBoolean("drag")

	BottomProperty = states.NewPropertyBoolean("bottom")

	HasBookProperty = states.NewPropertyBoolean("has_book")

	SignalFireProperty = states.NewPropertyBoolean("signal_fire")

	HoneyLevelProperty = states.NewPropertyInteger("honey_level", 0, 5)

	ChargesProperty = states.NewPropertyInteger("charges", 0, 4)

	CandlesProperty = states.NewPropertyInteger("candles", 1, 4)

	BloomProperty = states.NewPropertyBoolean("bloom")

	CanSummonProperty = states.NewPropertyBoolean("can_summon")

	ShriekingProperty = states.NewPropertyBoolean("shrieking")

	BerriesProperty = states.NewPropertyBoolean("berries")
)
