// Code generated by gen_particles.go DO NOT EDIT.
// Package particles stores information about particles in Minecraft.
package particles

// ID describes the numeric ID of a particle.
type ID uint32

// Particle describes information about a type of particle.
type Particle struct {
	ID   ID
	Name string
}

var (
	Explode = Particle{
		ID:   0,
		Name: "explode",
	}
	Largeexplode = Particle{
		ID:   1,
		Name: "largeexplode",
	}
	Hugeexplosion = Particle{
		ID:   2,
		Name: "hugeexplosion",
	}
	FireworksSpark = Particle{
		ID:   3,
		Name: "fireworksSpark",
	}
	Bubble = Particle{
		ID:   4,
		Name: "bubble",
	}
	Splash = Particle{
		ID:   5,
		Name: "splash",
	}
	Wake = Particle{
		ID:   6,
		Name: "wake",
	}
	Suspended = Particle{
		ID:   7,
		Name: "suspended",
	}
	Depthsuspend = Particle{
		ID:   8,
		Name: "depthsuspend",
	}
	Crit = Particle{
		ID:   9,
		Name: "crit",
	}
	MagicCrit = Particle{
		ID:   10,
		Name: "magicCrit",
	}
	Smoke = Particle{
		ID:   11,
		Name: "smoke",
	}
	Largesmoke = Particle{
		ID:   12,
		Name: "largesmoke",
	}
	Spell = Particle{
		ID:   13,
		Name: "spell",
	}
	InstantSpell = Particle{
		ID:   14,
		Name: "instantSpell",
	}
	MobSpell = Particle{
		ID:   15,
		Name: "mobSpell",
	}
	MobSpellAmbient = Particle{
		ID:   16,
		Name: "mobSpellAmbient",
	}
	WitchMagic = Particle{
		ID:   17,
		Name: "witchMagic",
	}
	DripWater = Particle{
		ID:   18,
		Name: "dripWater",
	}
	DripLava = Particle{
		ID:   19,
		Name: "dripLava",
	}
	AngryVillager = Particle{
		ID:   20,
		Name: "angryVillager",
	}
	HappyVillager = Particle{
		ID:   21,
		Name: "happyVillager",
	}
	Townaura = Particle{
		ID:   22,
		Name: "townaura",
	}
	Note = Particle{
		ID:   23,
		Name: "note",
	}
	Portal = Particle{
		ID:   24,
		Name: "portal",
	}
	Enchantmenttable = Particle{
		ID:   25,
		Name: "enchantmenttable",
	}
	Flame = Particle{
		ID:   26,
		Name: "flame",
	}
	Lava = Particle{
		ID:   27,
		Name: "lava",
	}
	Footstep = Particle{
		ID:   28,
		Name: "footstep",
	}
	Cloud = Particle{
		ID:   29,
		Name: "cloud",
	}
	Reddust = Particle{
		ID:   30,
		Name: "reddust",
	}
	Snowballpoof = Particle{
		ID:   31,
		Name: "snowballpoof",
	}
	Snowshovel = Particle{
		ID:   32,
		Name: "snowshovel",
	}
	Slime = Particle{
		ID:   33,
		Name: "slime",
	}
	Heart = Particle{
		ID:   34,
		Name: "heart",
	}
	Barrier = Particle{
		ID:   35,
		Name: "barrier",
	}
	Iconcrack = Particle{
		ID:   36,
		Name: "iconcrack",
	}
	Blockcrack = Particle{
		ID:   37,
		Name: "blockcrack",
	}
	Blockdust = Particle{
		ID:   38,
		Name: "blockdust",
	}
	Droplet = Particle{
		ID:   39,
		Name: "droplet",
	}
	Take = Particle{
		ID:   40,
		Name: "take",
	}
	Mobappearance = Particle{
		ID:   41,
		Name: "mobappearance",
	}
	Dragonbreath = Particle{
		ID:   42,
		Name: "dragonbreath",
	}
	EndRod = Particle{
		ID:   43,
		Name: "endRod",
	}
	DamageIndicator = Particle{
		ID:   44,
		Name: "damageIndicator",
	}
	SweepAttack = Particle{
		ID:   45,
		Name: "sweepAttack",
	}
	Fallingdust = Particle{
		ID:   46,
		Name: "fallingdust",
	}
	Totem = Particle{
		ID:   47,
		Name: "totem",
	}
	Spit = Particle{
		ID:   48,
		Name: "spit",
	}
)

// ByID is an index of minecraft instruments by their ID.
var ByID = map[ID]*Particle{
	0:  &Explode,
	1:  &Largeexplode,
	2:  &Hugeexplosion,
	3:  &FireworksSpark,
	4:  &Bubble,
	5:  &Splash,
	6:  &Wake,
	7:  &Suspended,
	8:  &Depthsuspend,
	9:  &Crit,
	10: &MagicCrit,
	11: &Smoke,
	12: &Largesmoke,
	13: &Spell,
	14: &InstantSpell,
	15: &MobSpell,
	16: &MobSpellAmbient,
	17: &WitchMagic,
	18: &DripWater,
	19: &DripLava,
	20: &AngryVillager,
	21: &HappyVillager,
	22: &Townaura,
	23: &Note,
	24: &Portal,
	25: &Enchantmenttable,
	26: &Flame,
	27: &Lava,
	28: &Footstep,
	29: &Cloud,
	30: &Reddust,
	31: &Snowballpoof,
	32: &Snowshovel,
	33: &Slime,
	34: &Heart,
	35: &Barrier,
	36: &Iconcrack,
	37: &Blockcrack,
	38: &Blockdust,
	39: &Droplet,
	40: &Take,
	41: &Mobappearance,
	42: &Dragonbreath,
	43: &EndRod,
	44: &DamageIndicator,
	45: &SweepAttack,
	46: &Fallingdust,
	47: &Totem,
	48: &Spit,
}
