// Code generated by gen_item.go DO NOT EDIT.
// Package item stores information about items in Minecraft.
package item

// ID describes the numeric ID of an item.
type ID uint32

// Item describes information about a type of item.
type Item struct {
	ID          ID
	DisplayName string
	Name        string
	StackSize   uint
}

var (
	Stone = Item{
		ID: 1,
		DisplayName: "Stone",
		Name: "stone",
		StackSize: 64,
	}
	Grass = Item{
		ID: 2,
		DisplayName: "Grass Block",
		Name: "grass",
		StackSize: 64,
	}
	Dirt = Item{
		ID: 3,
		DisplayName: "Dirt",
		Name: "dirt",
		StackSize: 64,
	}
	Cobblestone = Item{
		ID: 4,
		DisplayName: "Cobblestone",
		Name: "cobblestone",
		StackSize: 64,
	}
	Planks = Item{
		ID: 5,
		DisplayName: "Wooden Planks",
		Name: "planks",
		StackSize: 64,
	}
	Sapling = Item{
		ID: 6,
		DisplayName: "Sapling",
		Name: "sapling",
		StackSize: 64,
	}
	Bedrock = Item{
		ID: 7,
		DisplayName: "Bedrock",
		Name: "bedrock",
		StackSize: 64,
	}
	Sand = Item{
		ID: 12,
		DisplayName: "Sand",
		Name: "sand",
		StackSize: 64,
	}
	Gravel = Item{
		ID: 13,
		DisplayName: "Gravel",
		Name: "gravel",
		StackSize: 64,
	}
	GoldOre = Item{
		ID: 14,
		DisplayName: "Gold Ore",
		Name: "gold_ore",
		StackSize: 64,
	}
	IronOre = Item{
		ID: 15,
		DisplayName: "Iron Ore",
		Name: "iron_ore",
		StackSize: 64,
	}
	CoalOre = Item{
		ID: 16,
		DisplayName: "Coal Ore",
		Name: "coal_ore",
		StackSize: 64,
	}
	Log = Item{
		ID: 17,
		DisplayName: "Wood",
		Name: "log",
		StackSize: 64,
	}
	Leaves = Item{
		ID: 18,
		DisplayName: "Leaves",
		Name: "leaves",
		StackSize: 64,
	}
	Sponge = Item{
		ID: 19,
		DisplayName: "Sponge",
		Name: "sponge",
		StackSize: 64,
	}
	Glass = Item{
		ID: 20,
		DisplayName: "Glass",
		Name: "glass",
		StackSize: 64,
	}
	LapisOre = Item{
		ID: 21,
		DisplayName: "Lapis Lazuli Ore",
		Name: "lapis_ore",
		StackSize: 64,
	}
	LapisBlock = Item{
		ID: 22,
		DisplayName: "Lapis Lazuli Block",
		Name: "lapis_block",
		StackSize: 64,
	}
	Dispenser = Item{
		ID: 23,
		DisplayName: "Dispenser",
		Name: "dispenser",
		StackSize: 64,
	}
	Sandstone = Item{
		ID: 24,
		DisplayName: "Sandstone",
		Name: "sandstone",
		StackSize: 64,
	}
	Noteblock = Item{
		ID: 25,
		DisplayName: "Note Block",
		Name: "noteblock",
		StackSize: 64,
	}
	GoldenRail = Item{
		ID: 27,
		DisplayName: "Powered Rail",
		Name: "golden_rail",
		StackSize: 64,
	}
	DetectorRail = Item{
		ID: 28,
		DisplayName: "Detector Rail",
		Name: "detector_rail",
		StackSize: 64,
	}
	StickyPiston = Item{
		ID: 29,
		DisplayName: "Sticky Piston",
		Name: "sticky_piston",
		StackSize: 64,
	}
	Web = Item{
		ID: 30,
		DisplayName: "Cobweb",
		Name: "web",
		StackSize: 64,
	}
	Tallgrass = Item{
		ID: 31,
		DisplayName: "Grass",
		Name: "tallgrass",
		StackSize: 64,
	}
	Deadbush = Item{
		ID: 32,
		DisplayName: "Dead Bush",
		Name: "deadbush",
		StackSize: 64,
	}
	Piston = Item{
		ID: 33,
		DisplayName: "Piston",
		Name: "piston",
		StackSize: 64,
	}
	Wool = Item{
		ID: 35,
		DisplayName: "Wool",
		Name: "wool",
		StackSize: 64,
	}
	YellowFlower = Item{
		ID: 37,
		DisplayName: "Dandelion",
		Name: "yellow_flower",
		StackSize: 64,
	}
	RedFlower = Item{
		ID: 38,
		DisplayName: "Poppy",
		Name: "red_flower",
		StackSize: 64,
	}
	BrownMushroom = Item{
		ID: 39,
		DisplayName: "Brown Mushroom",
		Name: "brown_mushroom",
		StackSize: 64,
	}
	RedMushroom = Item{
		ID: 40,
		DisplayName: "Red Mushroom",
		Name: "red_mushroom",
		StackSize: 64,
	}
	GoldBlock = Item{
		ID: 41,
		DisplayName: "Block of Gold",
		Name: "gold_block",
		StackSize: 64,
	}
	IronBlock = Item{
		ID: 42,
		DisplayName: "Block of Iron",
		Name: "iron_block",
		StackSize: 64,
	}
	StoneSlab = Item{
		ID: 44,
		DisplayName: "Stone Slab",
		Name: "stone_slab",
		StackSize: 64,
	}
	BrickBlock = Item{
		ID: 45,
		DisplayName: "Brick",
		Name: "brick_block",
		StackSize: 64,
	}
	Tnt = Item{
		ID: 46,
		DisplayName: "TNT",
		Name: "tnt",
		StackSize: 64,
	}
	Bookshelf = Item{
		ID: 47,
		DisplayName: "Bookshelf",
		Name: "bookshelf",
		StackSize: 64,
	}
	MossyCobblestone = Item{
		ID: 48,
		DisplayName: "Moss Stone",
		Name: "mossy_cobblestone",
		StackSize: 64,
	}
	Obsidian = Item{
		ID: 49,
		DisplayName: "Obsidian",
		Name: "obsidian",
		StackSize: 64,
	}
	Torch = Item{
		ID: 50,
		DisplayName: "Torch",
		Name: "torch",
		StackSize: 64,
	}
	MobSpawner = Item{
		ID: 52,
		DisplayName: "Monster Spawner",
		Name: "mob_spawner",
		StackSize: 64,
	}
	OakStairs = Item{
		ID: 53,
		DisplayName: "Oak Wood Stairs",
		Name: "oak_stairs",
		StackSize: 64,
	}
	Chest = Item{
		ID: 54,
		DisplayName: "Chest",
		Name: "chest",
		StackSize: 64,
	}
	DiamondOre = Item{
		ID: 56,
		DisplayName: "Diamond Ore",
		Name: "diamond_ore",
		StackSize: 64,
	}
	DiamondBlock = Item{
		ID: 57,
		DisplayName: "Block of Diamond",
		Name: "diamond_block",
		StackSize: 64,
	}
	CraftingTable = Item{
		ID: 58,
		DisplayName: "Crafting Table",
		Name: "crafting_table",
		StackSize: 64,
	}
	Farmland = Item{
		ID: 60,
		DisplayName: "Farmland",
		Name: "farmland",
		StackSize: 64,
	}
	Furnace = Item{
		ID: 61,
		DisplayName: "Furnace",
		Name: "furnace",
		StackSize: 64,
	}
	Ladder = Item{
		ID: 65,
		DisplayName: "Ladder",
		Name: "ladder",
		StackSize: 64,
	}
	Rail = Item{
		ID: 66,
		DisplayName: "Rail",
		Name: "rail",
		StackSize: 64,
	}
	StoneStairs = Item{
		ID: 67,
		DisplayName: "Cobblestone Stairs",
		Name: "stone_stairs",
		StackSize: 64,
	}
	Lever = Item{
		ID: 69,
		DisplayName: "Lever",
		Name: "lever",
		StackSize: 64,
	}
	StonePressurePlate = Item{
		ID: 70,
		DisplayName: "Stone Pressure Plate",
		Name: "stone_pressure_plate",
		StackSize: 64,
	}
	WoodenPressurePlate = Item{
		ID: 72,
		DisplayName: "Wooden Pressure Plate",
		Name: "wooden_pressure_plate",
		StackSize: 64,
	}
	RedstoneOre = Item{
		ID: 73,
		DisplayName: "Redstone Ore",
		Name: "redstone_ore",
		StackSize: 64,
	}
	RedstoneTorch = Item{
		ID: 76,
		DisplayName: "Redstone Torch",
		Name: "redstone_torch",
		StackSize: 64,
	}
	StoneButton = Item{
		ID: 77,
		DisplayName: "Stone Button",
		Name: "stone_button",
		StackSize: 64,
	}
	SnowLayer = Item{
		ID: 78,
		DisplayName: "Snow",
		Name: "snow_layer",
		StackSize: 64,
	}
	Ice = Item{
		ID: 79,
		DisplayName: "Ice",
		Name: "ice",
		StackSize: 64,
	}
	Snow = Item{
		ID: 80,
		DisplayName: "Snow",
		Name: "snow",
		StackSize: 64,
	}
	Cactus = Item{
		ID: 81,
		DisplayName: "Cactus",
		Name: "cactus",
		StackSize: 64,
	}
	Clay = Item{
		ID: 82,
		DisplayName: "Clay",
		Name: "clay",
		StackSize: 64,
	}
	Jukebox = Item{
		ID: 84,
		DisplayName: "Jukebox",
		Name: "jukebox",
		StackSize: 64,
	}
	Fence = Item{
		ID: 85,
		DisplayName: "Oak Fence",
		Name: "fence",
		StackSize: 64,
	}
	Pumpkin = Item{
		ID: 86,
		DisplayName: "Pumpkin",
		Name: "pumpkin",
		StackSize: 64,
	}
	Netherrack = Item{
		ID: 87,
		DisplayName: "Netherrack",
		Name: "netherrack",
		StackSize: 64,
	}
	SoulSand = Item{
		ID: 88,
		DisplayName: "Soul Sand",
		Name: "soul_sand",
		StackSize: 64,
	}
	Glowstone = Item{
		ID: 89,
		DisplayName: "Glowstone",
		Name: "glowstone",
		StackSize: 64,
	}
	LitPumpkin = Item{
		ID: 91,
		DisplayName: "Jack o'Lantern",
		Name: "lit_pumpkin",
		StackSize: 64,
	}
	StainedGlass = Item{
		ID: 95,
		DisplayName: "Stained Glass",
		Name: "stained_glass",
		StackSize: 64,
	}
	Trapdoor = Item{
		ID: 96,
		DisplayName: "Wooden Trapdoor",
		Name: "trapdoor",
		StackSize: 64,
	}
	MonsterEgg = Item{
		ID: 97,
		DisplayName: "Monster Egg",
		Name: "monster_egg",
		StackSize: 64,
	}
	Stonebrick = Item{
		ID: 98,
		DisplayName: "Stone Bricks",
		Name: "stonebrick",
		StackSize: 64,
	}
	BrownMushroomBlock = Item{
		ID: 99,
		DisplayName: "Brown Mushroom Block",
		Name: "brown_mushroom_block",
		StackSize: 64,
	}
	RedMushroomBlock = Item{
		ID: 100,
		DisplayName: "Red Mushroom Block",
		Name: "red_mushroom_block",
		StackSize: 64,
	}
	IronBars = Item{
		ID: 101,
		DisplayName: "Iron Bars",
		Name: "iron_bars",
		StackSize: 64,
	}
	GlassPane = Item{
		ID: 102,
		DisplayName: "Glass Pane",
		Name: "glass_pane",
		StackSize: 64,
	}
	MelonBlock = Item{
		ID: 103,
		DisplayName: "Melon",
		Name: "melon_block",
		StackSize: 64,
	}
	Vine = Item{
		ID: 106,
		DisplayName: "Vines",
		Name: "vine",
		StackSize: 64,
	}
	FenceGate = Item{
		ID: 107,
		DisplayName: "Oak Fence Gate",
		Name: "fence_gate",
		StackSize: 64,
	}
	BrickStairs = Item{
		ID: 108,
		DisplayName: "Brick Stairs",
		Name: "brick_stairs",
		StackSize: 64,
	}
	StoneBrickStairs = Item{
		ID: 109,
		DisplayName: "Stone Brick Stairs",
		Name: "stone_brick_stairs",
		StackSize: 64,
	}
	Mycelium = Item{
		ID: 110,
		DisplayName: "Mycelium",
		Name: "mycelium",
		StackSize: 64,
	}
	Waterlily = Item{
		ID: 111,
		DisplayName: "Lily Pad",
		Name: "waterlily",
		StackSize: 64,
	}
	NetherBrick = Item{
		ID: 112,
		DisplayName: "Nether Brick",
		Name: "nether_brick",
		StackSize: 64,
	}
	NetherBrickFence = Item{
		ID: 113,
		DisplayName: "Nether Brick Fence",
		Name: "nether_brick_fence",
		StackSize: 64,
	}
	NetherBrickStairs = Item{
		ID: 114,
		DisplayName: "Nether Brick Stairs",
		Name: "nether_brick_stairs",
		StackSize: 64,
	}
	EnchantingTable = Item{
		ID: 116,
		DisplayName: "Enchantment Table",
		Name: "enchanting_table",
		StackSize: 64,
	}
	EndPortalFrame = Item{
		ID: 120,
		DisplayName: "End Portal Frame",
		Name: "end_portal_frame",
		StackSize: 64,
	}
	EndStone = Item{
		ID: 121,
		DisplayName: "End Stone",
		Name: "end_stone",
		StackSize: 64,
	}
	DragonEgg = Item{
		ID: 122,
		DisplayName: "Dragon Egg",
		Name: "dragon_egg",
		StackSize: 64,
	}
	RedstoneLamp = Item{
		ID: 123,
		DisplayName: "Redstone Lamp",
		Name: "redstone_lamp",
		StackSize: 64,
	}
	WoodenSlab = Item{
		ID: 126,
		DisplayName: "Wood Slab",
		Name: "wooden_slab",
		StackSize: 64,
	}
	SandstoneStairs = Item{
		ID: 128,
		DisplayName: "Sandstone Stairs",
		Name: "sandstone_stairs",
		StackSize: 64,
	}
	EmeraldOre = Item{
		ID: 129,
		DisplayName: "Emerald Ore",
		Name: "emerald_ore",
		StackSize: 64,
	}
	EnderChest = Item{
		ID: 130,
		DisplayName: "Ender Chest",
		Name: "ender_chest",
		StackSize: 64,
	}
	TripwireHook = Item{
		ID: 131,
		DisplayName: "Tripwire Hook",
		Name: "tripwire_hook",
		StackSize: 64,
	}
	EmeraldBlock = Item{
		ID: 133,
		DisplayName: "Block of Emerald",
		Name: "emerald_block",
		StackSize: 64,
	}
	SpruceStairs = Item{
		ID: 134,
		DisplayName: "Spruce Wood Stairs",
		Name: "spruce_stairs",
		StackSize: 64,
	}
	BirchStairs = Item{
		ID: 135,
		DisplayName: "Birch Wood Stairs",
		Name: "birch_stairs",
		StackSize: 64,
	}
	JungleStairs = Item{
		ID: 136,
		DisplayName: "Jungle Wood Stairs",
		Name: "jungle_stairs",
		StackSize: 64,
	}
	CommandBlock = Item{
		ID: 137,
		DisplayName: "Command Block",
		Name: "command_block",
		StackSize: 64,
	}
	Beacon = Item{
		ID: 138,
		DisplayName: "Beacon",
		Name: "beacon",
		StackSize: 64,
	}
	CobblestoneWall = Item{
		ID: 139,
		DisplayName: "Cobblestone Wall",
		Name: "cobblestone_wall",
		StackSize: 64,
	}
	WoodenButton = Item{
		ID: 143,
		DisplayName: "Wooden Button",
		Name: "wooden_button",
		StackSize: 64,
	}
	Anvil = Item{
		ID: 145,
		DisplayName: "Anvil",
		Name: "anvil",
		StackSize: 64,
	}
	TrappedChest = Item{
		ID: 146,
		DisplayName: "Trapped Chest",
		Name: "trapped_chest",
		StackSize: 64,
	}
	LightWeightedPressurePlate = Item{
		ID: 147,
		DisplayName: "Weighted Pressure Plate (Light)",
		Name: "light_weighted_pressure_plate",
		StackSize: 64,
	}
	HeavyWeightedPressurePlate = Item{
		ID: 148,
		DisplayName: "Weighted Pressure Plate (Heavy)",
		Name: "heavy_weighted_pressure_plate",
		StackSize: 64,
	}
	DaylightDetector = Item{
		ID: 151,
		DisplayName: "Daylight Detector",
		Name: "daylight_detector",
		StackSize: 64,
	}
	RedstoneBlock = Item{
		ID: 152,
		DisplayName: "Block of Redstone",
		Name: "redstone_block",
		StackSize: 64,
	}
	QuartzOre = Item{
		ID: 153,
		DisplayName: "Nether Quartz",
		Name: "quartz_ore",
		StackSize: 64,
	}
	Hopper = Item{
		ID: 154,
		DisplayName: "Hopper",
		Name: "hopper",
		StackSize: 64,
	}
	QuartzBlock = Item{
		ID: 155,
		DisplayName: "Block of Quartz",
		Name: "quartz_block",
		StackSize: 64,
	}
	QuartzStairs = Item{
		ID: 156,
		DisplayName: "Quartz Stairs",
		Name: "quartz_stairs",
		StackSize: 64,
	}
	ActivatorRail = Item{
		ID: 157,
		DisplayName: "Activator Rail",
		Name: "activator_rail",
		StackSize: 64,
	}
	Dropper = Item{
		ID: 158,
		DisplayName: "Dropper",
		Name: "dropper",
		StackSize: 64,
	}
	StainedHardenedClay = Item{
		ID: 159,
		DisplayName: "Stained Terracotta",
		Name: "stained_hardened_clay",
		StackSize: 64,
	}
	StainedGlassPane = Item{
		ID: 160,
		DisplayName: "Stained Glass Pane",
		Name: "stained_glass_pane",
		StackSize: 64,
	}
	Leaves2 = Item{
		ID: 161,
		DisplayName: "Leaves",
		Name: "leaves2",
		StackSize: 64,
	}
	Log2 = Item{
		ID: 162,
		DisplayName: "Wood",
		Name: "log2",
		StackSize: 64,
	}
	AcaciaStairs = Item{
		ID: 163,
		DisplayName: "Acacia Wood Stairs",
		Name: "acacia_stairs",
		StackSize: 64,
	}
	DarkOakStairs = Item{
		ID: 164,
		DisplayName: "Dark Oak Wood Stairs",
		Name: "dark_oak_stairs",
		StackSize: 64,
	}
	Slime = Item{
		ID: 165,
		DisplayName: "Slime Block",
		Name: "slime",
		StackSize: 64,
	}
	Barrier = Item{
		ID: 166,
		DisplayName: "Barrier",
		Name: "barrier",
		StackSize: 64,
	}
	IronTrapdoor = Item{
		ID: 167,
		DisplayName: "Iron Trapdoor",
		Name: "iron_trapdoor",
		StackSize: 64,
	}
	Prismarine = Item{
		ID: 168,
		DisplayName: "Prismarine",
		Name: "prismarine",
		StackSize: 64,
	}
	SeaLantern = Item{
		ID: 169,
		DisplayName: "Sea Lantern",
		Name: "sea_lantern",
		StackSize: 64,
	}
	HayBlock = Item{
		ID: 170,
		DisplayName: "Hay Bale",
		Name: "hay_block",
		StackSize: 64,
	}
	Carpet = Item{
		ID: 171,
		DisplayName: "Carpet",
		Name: "carpet",
		StackSize: 64,
	}
	HardenedClay = Item{
		ID: 172,
		DisplayName: "Terracotta",
		Name: "hardened_clay",
		StackSize: 64,
	}
	CoalBlock = Item{
		ID: 173,
		DisplayName: "Block of Coal",
		Name: "coal_block",
		StackSize: 64,
	}
	PackedIce = Item{
		ID: 174,
		DisplayName: "Packed Ice",
		Name: "packed_ice",
		StackSize: 64,
	}
	DoublePlant = Item{
		ID: 175,
		DisplayName: "Large Flowers",
		Name: "double_plant",
		StackSize: 64,
	}
	RedSandstone = Item{
		ID: 179,
		DisplayName: "Red Sandstone",
		Name: "red_sandstone",
		StackSize: 64,
	}
	RedSandstoneStairs = Item{
		ID: 180,
		DisplayName: "Red Sandstone Stairs",
		Name: "red_sandstone_stairs",
		StackSize: 64,
	}
	StoneSlab2 = Item{
		ID: 182,
		DisplayName: "Red Sandstone Slab",
		Name: "stone_slab2",
		StackSize: 64,
	}
	SpruceFenceGate = Item{
		ID: 183,
		DisplayName: "Spruce Fence Gate",
		Name: "spruce_fence_gate",
		StackSize: 64,
	}
	BirchFenceGate = Item{
		ID: 184,
		DisplayName: "Birch Fence Gate",
		Name: "birch_fence_gate",
		StackSize: 64,
	}
	JungleFenceGate = Item{
		ID: 185,
		DisplayName: "Jungle Fence Gate",
		Name: "jungle_fence_gate",
		StackSize: 64,
	}
	DarkOakFenceGate = Item{
		ID: 186,
		DisplayName: "Dark Oak Fence Gate",
		Name: "dark_oak_fence_gate",
		StackSize: 64,
	}
	AcaciaFenceGate = Item{
		ID: 187,
		DisplayName: "Acacia Fence Gate",
		Name: "acacia_fence_gate",
		StackSize: 64,
	}
	SpruceFence = Item{
		ID: 188,
		DisplayName: "Spruce Fence",
		Name: "spruce_fence",
		StackSize: 64,
	}
	BirchFence = Item{
		ID: 189,
		DisplayName: "Birch Fence",
		Name: "birch_fence",
		StackSize: 64,
	}
	JungleFence = Item{
		ID: 190,
		DisplayName: "Jungle Fence",
		Name: "jungle_fence",
		StackSize: 64,
	}
	DarkOakFence = Item{
		ID: 191,
		DisplayName: "Dark Oak Fence",
		Name: "dark_oak_fence",
		StackSize: 64,
	}
	AcaciaFence = Item{
		ID: 192,
		DisplayName: "Acacia Fence",
		Name: "acacia_fence",
		StackSize: 64,
	}
	EndRod = Item{
		ID: 198,
		DisplayName: "End Rod",
		Name: "end_rod",
		StackSize: 64,
	}
	ChorusPlant = Item{
		ID: 199,
		DisplayName: "Chorus Plant",
		Name: "chorus_plant",
		StackSize: 64,
	}
	ChorusFlower = Item{
		ID: 200,
		DisplayName: "Chorus Flower",
		Name: "chorus_flower",
		StackSize: 64,
	}
	PurpurBlock = Item{
		ID: 201,
		DisplayName: "Purpur Block",
		Name: "purpur_block",
		StackSize: 64,
	}
	PurpurPillar = Item{
		ID: 202,
		DisplayName: "Purpur Pillar",
		Name: "purpur_pillar",
		StackSize: 64,
	}
	PurpurStairs = Item{
		ID: 203,
		DisplayName: "Purpur Stairs",
		Name: "purpur_stairs",
		StackSize: 64,
	}
	PurpurSlab = Item{
		ID: 205,
		DisplayName: "Purpur Slab",
		Name: "purpur_slab",
		StackSize: 64,
	}
	EndBricks = Item{
		ID: 206,
		DisplayName: "End Stone Bricks",
		Name: "end_bricks",
		StackSize: 64,
	}
	GrassPath = Item{
		ID: 208,
		DisplayName: "Grass Path",
		Name: "grass_path",
		StackSize: 64,
	}
	RepeatingCommandBlock = Item{
		ID: 210,
		DisplayName: "Repeating Command Block",
		Name: "repeating_command_block",
		StackSize: 64,
	}
	ChainCommandBlock = Item{
		ID: 211,
		DisplayName: "Chain Command Block",
		Name: "chain_command_block",
		StackSize: 64,
	}
	Magma = Item{
		ID: 213,
		DisplayName: "Magma Block",
		Name: "magma",
		StackSize: 64,
	}
	NetherWartBlock = Item{
		ID: 214,
		DisplayName: "Nether Wart Block",
		Name: "nether_wart_block",
		StackSize: 64,
	}
	RedNetherBrick = Item{
		ID: 215,
		DisplayName: "Red Nether Brick",
		Name: "red_nether_brick",
		StackSize: 64,
	}
	BoneBlock = Item{
		ID: 216,
		DisplayName: "Bone Block",
		Name: "bone_block",
		StackSize: 64,
	}
	StructureVoid = Item{
		ID: 217,
		DisplayName: "Structure Void",
		Name: "structure_void",
		StackSize: 64,
	}
	Observer = Item{
		ID: 218,
		DisplayName: "Observer",
		Name: "observer",
		StackSize: 64,
	}
	WhiteShulkerBox = Item{
		ID: 219,
		DisplayName: "White Shulker Box",
		Name: "white_shulker_box",
		StackSize: 1,
	}
	OrangeShulkerBox = Item{
		ID: 220,
		DisplayName: "Orange Shulker Box",
		Name: "orange_shulker_box",
		StackSize: 1,
	}
	MagentaShulkerBox = Item{
		ID: 221,
		DisplayName: "Magenta Shulker Box",
		Name: "magenta_shulker_box",
		StackSize: 1,
	}
	LightBlueShulkerBox = Item{
		ID: 222,
		DisplayName: "Light Blue Shulker Box",
		Name: "light_blue_shulker_box",
		StackSize: 1,
	}
	YellowShulkerBox = Item{
		ID: 223,
		DisplayName: "Yellow Shulker Box",
		Name: "yellow_shulker_box",
		StackSize: 1,
	}
	LimeShulkerBox = Item{
		ID: 224,
		DisplayName: "Lime Shulker Box",
		Name: "lime_shulker_box",
		StackSize: 1,
	}
	PinkShulkerBox = Item{
		ID: 225,
		DisplayName: "Pink Shulker Box",
		Name: "pink_shulker_box",
		StackSize: 1,
	}
	GrayShulkerBox = Item{
		ID: 226,
		DisplayName: "Gray Shulker Box",
		Name: "gray_shulker_box",
		StackSize: 1,
	}
	SilverShulkerBox = Item{
		ID: 227,
		DisplayName: "Light Gray Shulker Box",
		Name: "silver_shulker_box",
		StackSize: 1,
	}
	CyanShulkerBox = Item{
		ID: 228,
		DisplayName: "Cyan Shulker Box",
		Name: "cyan_shulker_box",
		StackSize: 1,
	}
	PurpleShulkerBox = Item{
		ID: 229,
		DisplayName: "Purple Shulker Box",
		Name: "purple_shulker_box",
		StackSize: 1,
	}
	BlueShulkerBox = Item{
		ID: 230,
		DisplayName: "Blue Shulker Box",
		Name: "blue_shulker_box",
		StackSize: 1,
	}
	BrownShulkerBox = Item{
		ID: 231,
		DisplayName: "Brown Shulker Box",
		Name: "brown_shulker_box",
		StackSize: 1,
	}
	GreenShulkerBox = Item{
		ID: 232,
		DisplayName: "Green Shulker Box",
		Name: "green_shulker_box",
		StackSize: 1,
	}
	RedShulkerBox = Item{
		ID: 233,
		DisplayName: "Red Shulker Box",
		Name: "red_shulker_box",
		StackSize: 1,
	}
	BlackShulkerBox = Item{
		ID: 234,
		DisplayName: "Black Shulker Box",
		Name: "black_shulker_box",
		StackSize: 1,
	}
	WhiteGlazedTerracotta = Item{
		ID: 235,
		DisplayName: "White Glazed Terracotta",
		Name: "white_glazed_terracotta",
		StackSize: 64,
	}
	OrangeGlazedTerracotta = Item{
		ID: 236,
		DisplayName: "Orange Glazed Terracotta",
		Name: "orange_glazed_terracotta",
		StackSize: 64,
	}
	MagentaGlazedTerracotta = Item{
		ID: 237,
		DisplayName: "Magenta Glazed Terracotta",
		Name: "magenta_glazed_terracotta",
		StackSize: 64,
	}
	LightBlueGlazedTerracotta = Item{
		ID: 238,
		DisplayName: "Light Blue Glazed Terracotta",
		Name: "light_blue_glazed_terracotta",
		StackSize: 64,
	}
	YellowGlazedTerracotta = Item{
		ID: 239,
		DisplayName: "Yellow Glazed Terracotta",
		Name: "yellow_glazed_terracotta",
		StackSize: 64,
	}
	LimeGlazedTerracotta = Item{
		ID: 240,
		DisplayName: "Lime Glazed Terracotta",
		Name: "lime_glazed_terracotta",
		StackSize: 64,
	}
	PinkGlazedTerracotta = Item{
		ID: 241,
		DisplayName: "Pink Glazed Terracotta",
		Name: "pink_glazed_terracotta",
		StackSize: 64,
	}
	GrayGlazedTerracotta = Item{
		ID: 242,
		DisplayName: "Gray Glazed Terracotta",
		Name: "gray_glazed_terracotta",
		StackSize: 64,
	}
	SilverGlazedTerracotta = Item{
		ID: 243,
		DisplayName: "Silver Glazed Terracotta",
		Name: "silver_glazed_terracotta",
		StackSize: 64,
	}
	CyanGlazedTerracotta = Item{
		ID: 244,
		DisplayName: "Cyan Glazed Terracotta",
		Name: "cyan_glazed_terracotta",
		StackSize: 64,
	}
	PurpleGlazedTerracotta = Item{
		ID: 245,
		DisplayName: "Purple Glazed Terracotta",
		Name: "purple_glazed_terracotta",
		StackSize: 64,
	}
	BlueGlazedTerracotta = Item{
		ID: 246,
		DisplayName: "Blue Glazed Terracotta",
		Name: "blue_glazed_terracotta",
		StackSize: 64,
	}
	BrownGlazedTerracotta = Item{
		ID: 247,
		DisplayName: "Brown Glazed Terracotta",
		Name: "brown_glazed_terracotta",
		StackSize: 64,
	}
	GreenGlazedTerracotta = Item{
		ID: 248,
		DisplayName: "Green Glazed Terracotta",
		Name: "green_glazed_terracotta",
		StackSize: 64,
	}
	RedGlazedTerracotta = Item{
		ID: 249,
		DisplayName: "Red Glazed Terracotta",
		Name: "red_glazed_terracotta",
		StackSize: 64,
	}
	BlackGlazedTerracotta = Item{
		ID: 250,
		DisplayName: "Black Glazed Terracotta",
		Name: "black_glazed_terracotta",
		StackSize: 64,
	}
	Concrete = Item{
		ID: 251,
		DisplayName: "Concrete",
		Name: "concrete",
		StackSize: 64,
	}
	ConcretePowder = Item{
		ID: 252,
		DisplayName: "Concrete Powder",
		Name: "concrete_powder",
		StackSize: 64,
	}
	StructureBlock = Item{
		ID: 255,
		DisplayName: "Structure Block",
		Name: "structure_block",
		StackSize: 64,
	}
	IronShovel = Item{
		ID: 256,
		DisplayName: "Iron Shovel",
		Name: "iron_shovel",
		StackSize: 1,
	}
	IronPickaxe = Item{
		ID: 257,
		DisplayName: "Iron Pickaxe",
		Name: "iron_pickaxe",
		StackSize: 1,
	}
	IronAxe = Item{
		ID: 258,
		DisplayName: "Iron Axe",
		Name: "iron_axe",
		StackSize: 1,
	}
	FlintAndSteel = Item{
		ID: 259,
		DisplayName: "Flint and Steel",
		Name: "flint_and_steel",
		StackSize: 1,
	}
	Apple = Item{
		ID: 260,
		DisplayName: "Apple",
		Name: "apple",
		StackSize: 64,
	}
	Bow = Item{
		ID: 261,
		DisplayName: "Bow",
		Name: "bow",
		StackSize: 1,
	}
	Arrow = Item{
		ID: 262,
		DisplayName: "Arrow",
		Name: "arrow",
		StackSize: 64,
	}
	Coal = Item{
		ID: 263,
		DisplayName: "Coal",
		Name: "coal",
		StackSize: 64,
	}
	Diamond = Item{
		ID: 264,
		DisplayName: "Diamond",
		Name: "diamond",
		StackSize: 64,
	}
	IronIngot = Item{
		ID: 265,
		DisplayName: "Iron Ingot",
		Name: "iron_ingot",
		StackSize: 64,
	}
	GoldIngot = Item{
		ID: 266,
		DisplayName: "Gold Ingot",
		Name: "gold_ingot",
		StackSize: 64,
	}
	IronSword = Item{
		ID: 267,
		DisplayName: "Iron Sword",
		Name: "iron_sword",
		StackSize: 1,
	}
	WoodenSword = Item{
		ID: 268,
		DisplayName: "Wooden Sword",
		Name: "wooden_sword",
		StackSize: 1,
	}
	WoodenShovel = Item{
		ID: 269,
		DisplayName: "Wooden Shovel",
		Name: "wooden_shovel",
		StackSize: 1,
	}
	WoodenPickaxe = Item{
		ID: 270,
		DisplayName: "Wooden Pickaxe",
		Name: "wooden_pickaxe",
		StackSize: 1,
	}
	WoodenAxe = Item{
		ID: 271,
		DisplayName: "Wooden Axe",
		Name: "wooden_axe",
		StackSize: 1,
	}
	StoneSword = Item{
		ID: 272,
		DisplayName: "Stone Sword",
		Name: "stone_sword",
		StackSize: 1,
	}
	StoneShovel = Item{
		ID: 273,
		DisplayName: "Stone Shovel",
		Name: "stone_shovel",
		StackSize: 1,
	}
	StonePickaxe = Item{
		ID: 274,
		DisplayName: "Stone Pickaxe",
		Name: "stone_pickaxe",
		StackSize: 1,
	}
	StoneAxe = Item{
		ID: 275,
		DisplayName: "Stone Axe",
		Name: "stone_axe",
		StackSize: 1,
	}
	DiamondSword = Item{
		ID: 276,
		DisplayName: "Diamond Sword",
		Name: "diamond_sword",
		StackSize: 1,
	}
	DiamondShovel = Item{
		ID: 277,
		DisplayName: "Diamond Shovel",
		Name: "diamond_shovel",
		StackSize: 1,
	}
	DiamondPickaxe = Item{
		ID: 278,
		DisplayName: "Diamond Pickaxe",
		Name: "diamond_pickaxe",
		StackSize: 1,
	}
	DiamondAxe = Item{
		ID: 279,
		DisplayName: "Diamond Axe",
		Name: "diamond_axe",
		StackSize: 1,
	}
	Stick = Item{
		ID: 280,
		DisplayName: "Stick",
		Name: "stick",
		StackSize: 64,
	}
	Bowl = Item{
		ID: 281,
		DisplayName: "Bowl",
		Name: "bowl",
		StackSize: 64,
	}
	MushroomStew = Item{
		ID: 282,
		DisplayName: "Mushroom Stew",
		Name: "mushroom_stew",
		StackSize: 1,
	}
	GoldenSword = Item{
		ID: 283,
		DisplayName: "Golden Sword",
		Name: "golden_sword",
		StackSize: 1,
	}
	GoldenShovel = Item{
		ID: 284,
		DisplayName: "Golden Shovel",
		Name: "golden_shovel",
		StackSize: 1,
	}
	GoldenPickaxe = Item{
		ID: 285,
		DisplayName: "Golden Pickaxe",
		Name: "golden_pickaxe",
		StackSize: 1,
	}
	GoldenAxe = Item{
		ID: 286,
		DisplayName: "Golden Axe",
		Name: "golden_axe",
		StackSize: 1,
	}
	String = Item{
		ID: 287,
		DisplayName: "String",
		Name: "string",
		StackSize: 64,
	}
	Feather = Item{
		ID: 288,
		DisplayName: "Feather",
		Name: "feather",
		StackSize: 64,
	}
	Gunpowder = Item{
		ID: 289,
		DisplayName: "Gunpowder",
		Name: "gunpowder",
		StackSize: 64,
	}
	WoodenHoe = Item{
		ID: 290,
		DisplayName: "Wooden Hoe",
		Name: "wooden_hoe",
		StackSize: 1,
	}
	StoneHoe = Item{
		ID: 291,
		DisplayName: "Stone Hoe",
		Name: "stone_hoe",
		StackSize: 1,
	}
	IronHoe = Item{
		ID: 292,
		DisplayName: "Iron Hoe",
		Name: "iron_hoe",
		StackSize: 1,
	}
	DiamondHoe = Item{
		ID: 293,
		DisplayName: "Diamond Hoe",
		Name: "diamond_hoe",
		StackSize: 1,
	}
	GoldenHoe = Item{
		ID: 294,
		DisplayName: "Golden Hoe",
		Name: "golden_hoe",
		StackSize: 1,
	}
	WheatSeeds = Item{
		ID: 295,
		DisplayName: "Seeds",
		Name: "wheat_seeds",
		StackSize: 64,
	}
	Wheat = Item{
		ID: 296,
		DisplayName: "Wheat",
		Name: "wheat",
		StackSize: 64,
	}
	Bread = Item{
		ID: 297,
		DisplayName: "Bread",
		Name: "bread",
		StackSize: 64,
	}
	LeatherHelmet = Item{
		ID: 298,
		DisplayName: "Leather Cap",
		Name: "leather_helmet",
		StackSize: 1,
	}
	LeatherChestplate = Item{
		ID: 299,
		DisplayName: "Leather Tunic",
		Name: "leather_chestplate",
		StackSize: 1,
	}
	LeatherLeggings = Item{
		ID: 300,
		DisplayName: "Leather Pants",
		Name: "leather_leggings",
		StackSize: 1,
	}
	LeatherBoots = Item{
		ID: 301,
		DisplayName: "Leather Boots",
		Name: "leather_boots",
		StackSize: 1,
	}
	ChainmailHelmet = Item{
		ID: 302,
		DisplayName: "Chain Helmet",
		Name: "chainmail_helmet",
		StackSize: 1,
	}
	ChainmailChestplate = Item{
		ID: 303,
		DisplayName: "Chain Chestplate",
		Name: "chainmail_chestplate",
		StackSize: 1,
	}
	ChainmailLeggings = Item{
		ID: 304,
		DisplayName: "Chain Leggings",
		Name: "chainmail_leggings",
		StackSize: 1,
	}
	ChainmailBoots = Item{
		ID: 305,
		DisplayName: "Chain Boots",
		Name: "chainmail_boots",
		StackSize: 1,
	}
	IronHelmet = Item{
		ID: 306,
		DisplayName: "Iron Helmet",
		Name: "iron_helmet",
		StackSize: 1,
	}
	IronChestplate = Item{
		ID: 307,
		DisplayName: "Iron Chestplate",
		Name: "iron_chestplate",
		StackSize: 1,
	}
	IronLeggings = Item{
		ID: 308,
		DisplayName: "Iron Leggings",
		Name: "iron_leggings",
		StackSize: 1,
	}
	IronBoots = Item{
		ID: 309,
		DisplayName: "Iron Boots",
		Name: "iron_boots",
		StackSize: 1,
	}
	DiamondHelmet = Item{
		ID: 310,
		DisplayName: "Diamond Helmet",
		Name: "diamond_helmet",
		StackSize: 1,
	}
	DiamondChestplate = Item{
		ID: 311,
		DisplayName: "Diamond Chestplate",
		Name: "diamond_chestplate",
		StackSize: 1,
	}
	DiamondLeggings = Item{
		ID: 312,
		DisplayName: "Diamond Leggings",
		Name: "diamond_leggings",
		StackSize: 1,
	}
	DiamondBoots = Item{
		ID: 313,
		DisplayName: "Diamond Boots",
		Name: "diamond_boots",
		StackSize: 1,
	}
	GoldenHelmet = Item{
		ID: 314,
		DisplayName: "Golden Helmet",
		Name: "golden_helmet",
		StackSize: 1,
	}
	GoldenChestplate = Item{
		ID: 315,
		DisplayName: "Golden Chestplate",
		Name: "golden_chestplate",
		StackSize: 1,
	}
	GoldenLeggings = Item{
		ID: 316,
		DisplayName: "Golden Leggings",
		Name: "golden_leggings",
		StackSize: 1,
	}
	GoldenBoots = Item{
		ID: 317,
		DisplayName: "Golden Boots",
		Name: "golden_boots",
		StackSize: 1,
	}
	Flint = Item{
		ID: 318,
		DisplayName: "Flint",
		Name: "flint",
		StackSize: 64,
	}
	Porkchop = Item{
		ID: 319,
		DisplayName: "Raw Porkchop",
		Name: "porkchop",
		StackSize: 64,
	}
	CookedPorkchop = Item{
		ID: 320,
		DisplayName: "Cooked Porkchop",
		Name: "cooked_porkchop",
		StackSize: 64,
	}
	Painting = Item{
		ID: 321,
		DisplayName: "Painting",
		Name: "painting",
		StackSize: 64,
	}
	GoldenApple = Item{
		ID: 322,
		DisplayName: "Golden Apple",
		Name: "golden_apple",
		StackSize: 64,
	}
	Sign = Item{
		ID: 323,
		DisplayName: "Sign",
		Name: "sign",
		StackSize: 16,
	}
	WoodenDoor = Item{
		ID: 324,
		DisplayName: "Oak Door",
		Name: "wooden_door",
		StackSize: 64,
	}
	Bucket = Item{
		ID: 325,
		DisplayName: "Bucket",
		Name: "bucket",
		StackSize: 16,
	}
	WaterBucket = Item{
		ID: 326,
		DisplayName: "Water Bucket",
		Name: "water_bucket",
		StackSize: 1,
	}
	LavaBucket = Item{
		ID: 327,
		DisplayName: "Lava Bucket",
		Name: "lava_bucket",
		StackSize: 1,
	}
	Minecart = Item{
		ID: 328,
		DisplayName: "Minecart",
		Name: "minecart",
		StackSize: 1,
	}
	Saddle = Item{
		ID: 329,
		DisplayName: "Saddle",
		Name: "saddle",
		StackSize: 1,
	}
	IronDoor = Item{
		ID: 330,
		DisplayName: "Iron Door",
		Name: "iron_door",
		StackSize: 64,
	}
	Redstone = Item{
		ID: 331,
		DisplayName: "Redstone",
		Name: "redstone",
		StackSize: 64,
	}
	Snowball = Item{
		ID: 332,
		DisplayName: "Snowball",
		Name: "snowball",
		StackSize: 16,
	}
	Boat = Item{
		ID: 333,
		DisplayName: "Boat",
		Name: "boat",
		StackSize: 1,
	}
	Leather = Item{
		ID: 334,
		DisplayName: "Leather",
		Name: "leather",
		StackSize: 64,
	}
	MilkBucket = Item{
		ID: 335,
		DisplayName: "Milk",
		Name: "milk_bucket",
		StackSize: 1,
	}
	Brick = Item{
		ID: 336,
		DisplayName: "Brick",
		Name: "brick",
		StackSize: 64,
	}
	ClayBall = Item{
		ID: 337,
		DisplayName: "Clay",
		Name: "clay_ball",
		StackSize: 64,
	}
	Reeds = Item{
		ID: 338,
		DisplayName: "Sugar Canes",
		Name: "reeds",
		StackSize: 64,
	}
	Paper = Item{
		ID: 339,
		DisplayName: "Paper",
		Name: "paper",
		StackSize: 64,
	}
	Book = Item{
		ID: 340,
		DisplayName: "Book",
		Name: "book",
		StackSize: 64,
	}
	SlimeBall = Item{
		ID: 341,
		DisplayName: "Slimeball",
		Name: "slime_ball",
		StackSize: 64,
	}
	ChestMinecart = Item{
		ID: 342,
		DisplayName: "Minecart with Chest",
		Name: "chest_minecart",
		StackSize: 1,
	}
	FurnaceMinecart = Item{
		ID: 343,
		DisplayName: "Minecart with Furnace",
		Name: "furnace_minecart",
		StackSize: 1,
	}
	Egg = Item{
		ID: 344,
		DisplayName: "Egg",
		Name: "egg",
		StackSize: 16,
	}
	Compass = Item{
		ID: 345,
		DisplayName: "Compass",
		Name: "compass",
		StackSize: 64,
	}
	FishingRod = Item{
		ID: 346,
		DisplayName: "Fishing Rod",
		Name: "fishing_rod",
		StackSize: 1,
	}
	Clock = Item{
		ID: 347,
		DisplayName: "Clock",
		Name: "clock",
		StackSize: 64,
	}
	GlowstoneDust = Item{
		ID: 348,
		DisplayName: "Glowstone Dust",
		Name: "glowstone_dust",
		StackSize: 64,
	}
	Fish = Item{
		ID: 349,
		DisplayName: "Fish",
		Name: "fish",
		StackSize: 64,
	}
	CookedFish = Item{
		ID: 350,
		DisplayName: "Cooked Fish",
		Name: "cooked_fish",
		StackSize: 64,
	}
	Dye = Item{
		ID: 351,
		DisplayName: "Dye",
		Name: "dye",
		StackSize: 64,
	}
	Bone = Item{
		ID: 352,
		DisplayName: "Bone",
		Name: "bone",
		StackSize: 64,
	}
	Sugar = Item{
		ID: 353,
		DisplayName: "Sugar",
		Name: "sugar",
		StackSize: 64,
	}
	Cake = Item{
		ID: 354,
		DisplayName: "Cake",
		Name: "cake",
		StackSize: 1,
	}
	Bed = Item{
		ID: 355,
		DisplayName: "Bed",
		Name: "bed",
		StackSize: 1,
	}
	Repeater = Item{
		ID: 356,
		DisplayName: "Redstone Repeater",
		Name: "repeater",
		StackSize: 64,
	}
	Cookie = Item{
		ID: 357,
		DisplayName: "Cookie",
		Name: "cookie",
		StackSize: 64,
	}
	FilledMap = Item{
		ID: 358,
		DisplayName: "Map",
		Name: "filled_map",
		StackSize: 64,
	}
	Shears = Item{
		ID: 359,
		DisplayName: "Shears",
		Name: "shears",
		StackSize: 1,
	}
	Melon = Item{
		ID: 360,
		DisplayName: "Melon",
		Name: "melon",
		StackSize: 64,
	}
	PumpkinSeeds = Item{
		ID: 361,
		DisplayName: "Pumpkin Seeds",
		Name: "pumpkin_seeds",
		StackSize: 64,
	}
	MelonSeeds = Item{
		ID: 362,
		DisplayName: "Melon Seeds",
		Name: "melon_seeds",
		StackSize: 64,
	}
	Beef = Item{
		ID: 363,
		DisplayName: "Raw Beef",
		Name: "beef",
		StackSize: 64,
	}
	CookedBeef = Item{
		ID: 364,
		DisplayName: "Steak",
		Name: "cooked_beef",
		StackSize: 64,
	}
	Chicken = Item{
		ID: 365,
		DisplayName: "Raw Chicken",
		Name: "chicken",
		StackSize: 64,
	}
	CookedChicken = Item{
		ID: 366,
		DisplayName: "Cooked Chicken",
		Name: "cooked_chicken",
		StackSize: 64,
	}
	RottenFlesh = Item{
		ID: 367,
		DisplayName: "Rotten Flesh",
		Name: "rotten_flesh",
		StackSize: 64,
	}
	EnderPearl = Item{
		ID: 368,
		DisplayName: "Ender Pearl",
		Name: "ender_pearl",
		StackSize: 16,
	}
	BlazeRod = Item{
		ID: 369,
		DisplayName: "Blaze Rod",
		Name: "blaze_rod",
		StackSize: 64,
	}
	GhastTear = Item{
		ID: 370,
		DisplayName: "Ghast Tear",
		Name: "ghast_tear",
		StackSize: 64,
	}
	GoldNugget = Item{
		ID: 371,
		DisplayName: "Gold Nugget",
		Name: "gold_nugget",
		StackSize: 64,
	}
	NetherWart = Item{
		ID: 372,
		DisplayName: "Nether Wart",
		Name: "nether_wart",
		StackSize: 64,
	}
	Potion = Item{
		ID: 373,
		DisplayName: "Potion",
		Name: "potion",
		StackSize: 1,
	}
	GlassBottle = Item{
		ID: 374,
		DisplayName: "Glass Bottle",
		Name: "glass_bottle",
		StackSize: 64,
	}
	SpiderEye = Item{
		ID: 375,
		DisplayName: "Spider Eye",
		Name: "spider_eye",
		StackSize: 64,
	}
	FermentedSpiderEye = Item{
		ID: 376,
		DisplayName: "Fermented Spider Eye",
		Name: "fermented_spider_eye",
		StackSize: 64,
	}
	BlazePowder = Item{
		ID: 377,
		DisplayName: "Blaze Powder",
		Name: "blaze_powder",
		StackSize: 64,
	}
	MagmaCream = Item{
		ID: 378,
		DisplayName: "Magma Cream",
		Name: "magma_cream",
		StackSize: 64,
	}
	BrewingStand = Item{
		ID: 379,
		DisplayName: "Brewing Stand",
		Name: "brewing_stand",
		StackSize: 64,
	}
	Cauldron = Item{
		ID: 380,
		DisplayName: "Cauldron",
		Name: "cauldron",
		StackSize: 64,
	}
	EnderEye = Item{
		ID: 381,
		DisplayName: "Eye of Ender",
		Name: "ender_eye",
		StackSize: 64,
	}
	SpeckledMelon = Item{
		ID: 382,
		DisplayName: "Glistering Melon",
		Name: "speckled_melon",
		StackSize: 64,
	}
	SpawnEgg = Item{
		ID: 383,
		DisplayName: "Spawn Egg",
		Name: "spawn_egg",
		StackSize: 64,
	}
	ExperienceBottle = Item{
		ID: 384,
		DisplayName: "Bottle o' Enchanting",
		Name: "experience_bottle",
		StackSize: 64,
	}
	FireCharge = Item{
		ID: 385,
		DisplayName: "Fire Charge",
		Name: "fire_charge",
		StackSize: 64,
	}
	WritableBook = Item{
		ID: 386,
		DisplayName: "Book and Quill",
		Name: "writable_book",
		StackSize: 1,
	}
	WrittenBook = Item{
		ID: 387,
		DisplayName: "Written Book",
		Name: "written_book",
		StackSize: 16,
	}
	Emerald = Item{
		ID: 388,
		DisplayName: "Emerald",
		Name: "emerald",
		StackSize: 64,
	}
	ItemFrame = Item{
		ID: 389,
		DisplayName: "Item Frame",
		Name: "item_frame",
		StackSize: 64,
	}
	FlowerPot = Item{
		ID: 390,
		DisplayName: "Flower Pot",
		Name: "flower_pot",
		StackSize: 64,
	}
	Carrot = Item{
		ID: 391,
		DisplayName: "Carrot",
		Name: "carrot",
		StackSize: 64,
	}
	Potato = Item{
		ID: 392,
		DisplayName: "Potato",
		Name: "potato",
		StackSize: 64,
	}
	BakedPotato = Item{
		ID: 393,
		DisplayName: "Baked Potato",
		Name: "baked_potato",
		StackSize: 64,
	}
	PoisonousPotato = Item{
		ID: 394,
		DisplayName: "Poisonous Potato",
		Name: "poisonous_potato",
		StackSize: 64,
	}
	Map = Item{
		ID: 395,
		DisplayName: "Empty Map",
		Name: "map",
		StackSize: 64,
	}
	GoldenCarrot = Item{
		ID: 396,
		DisplayName: "Golden Carrot",
		Name: "golden_carrot",
		StackSize: 64,
	}
	Skull = Item{
		ID: 397,
		DisplayName: "Skull",
		Name: "skull",
		StackSize: 64,
	}
	CarrotOnAStick = Item{
		ID: 398,
		DisplayName: "Carrot on a Stick",
		Name: "carrot_on_a_stick",
		StackSize: 1,
	}
	NetherStar = Item{
		ID: 399,
		DisplayName: "Nether Star",
		Name: "nether_star",
		StackSize: 64,
	}
	PumpkinPie = Item{
		ID: 400,
		DisplayName: "Pumpkin Pie",
		Name: "pumpkin_pie",
		StackSize: 64,
	}
	Fireworks = Item{
		ID: 401,
		DisplayName: "Firework Rocket",
		Name: "fireworks",
		StackSize: 64,
	}
	FireworkCharge = Item{
		ID: 402,
		DisplayName: "Firework Star",
		Name: "firework_charge",
		StackSize: 64,
	}
	EnchantedBook = Item{
		ID: 403,
		DisplayName: "Enchanted Book",
		Name: "enchanted_book",
		StackSize: 1,
	}
	Comparator = Item{
		ID: 404,
		DisplayName: "Redstone Comparator",
		Name: "comparator",
		StackSize: 64,
	}
	Netherbrick = Item{
		ID: 405,
		DisplayName: "Nether Brick",
		Name: "netherbrick",
		StackSize: 64,
	}
	Quartz = Item{
		ID: 406,
		DisplayName: "Nether Quartz",
		Name: "quartz",
		StackSize: 64,
	}
	TntMinecart = Item{
		ID: 407,
		DisplayName: "Minecart with TNT",
		Name: "tnt_minecart",
		StackSize: 1,
	}
	HopperMinecart = Item{
		ID: 408,
		DisplayName: "Minecart with Hopper",
		Name: "hopper_minecart",
		StackSize: 1,
	}
	PrismarineShard = Item{
		ID: 409,
		DisplayName: "Prismarine Shard",
		Name: "prismarine_shard",
		StackSize: 64,
	}
	PrismarineCrystals = Item{
		ID: 410,
		DisplayName: "Prismarine Crystals",
		Name: "prismarine_crystals",
		StackSize: 64,
	}
	Rabbit = Item{
		ID: 411,
		DisplayName: "Raw Rabbit",
		Name: "rabbit",
		StackSize: 64,
	}
	CookedRabbit = Item{
		ID: 412,
		DisplayName: "Cooked Rabbit",
		Name: "cooked_rabbit",
		StackSize: 64,
	}
	RabbitStew = Item{
		ID: 413,
		DisplayName: "Rabbit Stew",
		Name: "rabbit_stew",
		StackSize: 1,
	}
	RabbitFoot = Item{
		ID: 414,
		DisplayName: "Rabbit's Foot",
		Name: "rabbit_foot",
		StackSize: 64,
	}
	RabbitHide = Item{
		ID: 415,
		DisplayName: "Rabbit Hide",
		Name: "rabbit_hide",
		StackSize: 64,
	}
	ArmorStand = Item{
		ID: 416,
		DisplayName: "Armor Stand",
		Name: "armor_stand",
		StackSize: 16,
	}
	IronHorseArmor = Item{
		ID: 417,
		DisplayName: "Iron Horse Armor",
		Name: "iron_horse_armor",
		StackSize: 1,
	}
	GoldenHorseArmor = Item{
		ID: 418,
		DisplayName: "Gold Horse Armor",
		Name: "golden_horse_armor",
		StackSize: 1,
	}
	DiamondHorseArmor = Item{
		ID: 419,
		DisplayName: "Diamond Horse Armor",
		Name: "diamond_horse_armor",
		StackSize: 1,
	}
	Lead = Item{
		ID: 420,
		DisplayName: "Lead",
		Name: "lead",
		StackSize: 64,
	}
	NameTag = Item{
		ID: 421,
		DisplayName: "Name Tag",
		Name: "name_tag",
		StackSize: 64,
	}
	CommandBlockMinecart = Item{
		ID: 422,
		DisplayName: "Minecart with Command Block",
		Name: "command_block_minecart",
		StackSize: 1,
	}
	Mutton = Item{
		ID: 423,
		DisplayName: "Raw Mutton",
		Name: "mutton",
		StackSize: 64,
	}
	CookedMutton = Item{
		ID: 424,
		DisplayName: "Cooked Mutton",
		Name: "cooked_mutton",
		StackSize: 64,
	}
	Banner = Item{
		ID: 425,
		DisplayName: "Banner",
		Name: "banner",
		StackSize: 16,
	}
	EndCrystal = Item{
		ID: 426,
		DisplayName: "End Crystal",
		Name: "end_crystal",
		StackSize: 64,
	}
	SpruceDoor = Item{
		ID: 427,
		DisplayName: "Spruce Door",
		Name: "spruce_door",
		StackSize: 64,
	}
	BirchDoor = Item{
		ID: 428,
		DisplayName: "Birch Door",
		Name: "birch_door",
		StackSize: 64,
	}
	JungleDoor = Item{
		ID: 429,
		DisplayName: "Jungle Door",
		Name: "jungle_door",
		StackSize: 64,
	}
	AcaciaDoor = Item{
		ID: 430,
		DisplayName: "Acacia Door",
		Name: "acacia_door",
		StackSize: 64,
	}
	DarkOakDoor = Item{
		ID: 431,
		DisplayName: "Dark Oak Door",
		Name: "dark_oak_door",
		StackSize: 64,
	}
	ChorusFruit = Item{
		ID: 432,
		DisplayName: "Chorus Fruit",
		Name: "chorus_fruit",
		StackSize: 64,
	}
	ChorusFruitPopped = Item{
		ID: 433,
		DisplayName: "Popped Chorus Fruit",
		Name: "chorus_fruit_popped",
		StackSize: 64,
	}
	Beetroot = Item{
		ID: 434,
		DisplayName: "Beetroot",
		Name: "beetroot",
		StackSize: 64,
	}
	BeetrootSeeds = Item{
		ID: 435,
		DisplayName: "Beetroot Seeds",
		Name: "beetroot_seeds",
		StackSize: 64,
	}
	BeetrootSoup = Item{
		ID: 436,
		DisplayName: "Beetroot Soup",
		Name: "beetroot_soup",
		StackSize: 1,
	}
	DragonBreath = Item{
		ID: 437,
		DisplayName: "Dragon's Breath",
		Name: "dragon_breath",
		StackSize: 64,
	}
	SplashPotion = Item{
		ID: 438,
		DisplayName: "Splash Potion",
		Name: "splash_potion",
		StackSize: 1,
	}
	SpectralArrow = Item{
		ID: 439,
		DisplayName: "Spectral Arrow",
		Name: "spectral_arrow",
		StackSize: 64,
	}
	TippedArrow = Item{
		ID: 440,
		DisplayName: "Tipped Arrow",
		Name: "tipped_arrow",
		StackSize: 64,
	}
	LingeringPotion = Item{
		ID: 441,
		DisplayName: "Lingering Potion",
		Name: "lingering_potion",
		StackSize: 1,
	}
	Shield = Item{
		ID: 442,
		DisplayName: "Shield",
		Name: "shield",
		StackSize: 1,
	}
	Elytra = Item{
		ID: 443,
		DisplayName: "Elytra",
		Name: "elytra",
		StackSize: 1,
	}
	SpruceBoat = Item{
		ID: 444,
		DisplayName: "Spruce Boat",
		Name: "spruce_boat",
		StackSize: 1,
	}
	BirchBoat = Item{
		ID: 445,
		DisplayName: "Birch Boat",
		Name: "birch_boat",
		StackSize: 1,
	}
	JungleBoat = Item{
		ID: 446,
		DisplayName: "Jungle Boat",
		Name: "jungle_boat",
		StackSize: 1,
	}
	AcaciaBoat = Item{
		ID: 447,
		DisplayName: "Acacia Boat",
		Name: "acacia_boat",
		StackSize: 1,
	}
	DarkOakBoat = Item{
		ID: 448,
		DisplayName: "Dark Oak Boat",
		Name: "dark_oak_boat",
		StackSize: 1,
	}
	TotemOfUndying = Item{
		ID: 449,
		DisplayName: "Totem of Undying",
		Name: "totem_of_undying",
		StackSize: 1,
	}
	ShulkerShell = Item{
		ID: 450,
		DisplayName: "Shulker Shell",
		Name: "shulker_shell",
		StackSize: 64,
	}
	IronNugget = Item{
		ID: 452,
		DisplayName: "Iron Nugget",
		Name: "iron_nugget",
		StackSize: 64,
	}
	KnowledgeBook = Item{
		ID: 453,
		DisplayName: "Knowledge Book",
		Name: "knowledge_book",
		StackSize: 64,
	}
	Record13 = Item{
		ID: 2256,
		DisplayName: "13 Disc",
		Name: "record_13",
		StackSize: 64,
	}
	RecordCat = Item{
		ID: 2257,
		DisplayName: "Cat Disc",
		Name: "record_cat",
		StackSize: 1,
	}
	RecordBlocks = Item{
		ID: 2258,
		DisplayName: "Blocks Disc",
		Name: "record_blocks",
		StackSize: 1,
	}
	RecordChirp = Item{
		ID: 2259,
		DisplayName: "Chirp Disc",
		Name: "record_chirp",
		StackSize: 1,
	}
	RecordFar = Item{
		ID: 2260,
		DisplayName: "Far Disc",
		Name: "record_far",
		StackSize: 1,
	}
	RecordMall = Item{
		ID: 2261,
		DisplayName: "Mall Disc",
		Name: "record_mall",
		StackSize: 1,
	}
	RecordMellohi = Item{
		ID: 2262,
		DisplayName: "Mellohi Disc",
		Name: "record_mellohi",
		StackSize: 1,
	}
	RecordStal = Item{
		ID: 2263,
		DisplayName: "Stal Disc",
		Name: "record_stal",
		StackSize: 1,
	}
	RecordStrad = Item{
		ID: 2264,
		DisplayName: "Strad Disc",
		Name: "record_strad",
		StackSize: 1,
	}
	RecordWard = Item{
		ID: 2265,
		DisplayName: "Ward Disc",
		Name: "record_ward",
		StackSize: 1,
	}
	Record11 = Item{
		ID: 2266,
		DisplayName: "11 Disc",
		Name: "record_11",
		StackSize: 1,
	}
	RecordWait = Item{
		ID: 2267,
		DisplayName: "Wait Disc",
		Name: "record_wait",
		StackSize: 1,
	}
)

// ByID is an index of minecraft items by their ID.
var ByID = map[ID]*Item{ 
	1: &Stone,
	2: &Grass,
	3: &Dirt,
	4: &Cobblestone,
	5: &Planks,
	6: &Sapling,
	7: &Bedrock,
	12: &Sand,
	13: &Gravel,
	14: &GoldOre,
	15: &IronOre,
	16: &CoalOre,
	17: &Log,
	18: &Leaves,
	19: &Sponge,
	20: &Glass,
	21: &LapisOre,
	22: &LapisBlock,
	23: &Dispenser,
	24: &Sandstone,
	25: &Noteblock,
	27: &GoldenRail,
	28: &DetectorRail,
	29: &StickyPiston,
	30: &Web,
	31: &Tallgrass,
	32: &Deadbush,
	33: &Piston,
	35: &Wool,
	37: &YellowFlower,
	38: &RedFlower,
	39: &BrownMushroom,
	40: &RedMushroom,
	41: &GoldBlock,
	42: &IronBlock,
	44: &StoneSlab,
	45: &BrickBlock,
	46: &Tnt,
	47: &Bookshelf,
	48: &MossyCobblestone,
	49: &Obsidian,
	50: &Torch,
	52: &MobSpawner,
	53: &OakStairs,
	54: &Chest,
	56: &DiamondOre,
	57: &DiamondBlock,
	58: &CraftingTable,
	60: &Farmland,
	61: &Furnace,
	65: &Ladder,
	66: &Rail,
	67: &StoneStairs,
	69: &Lever,
	70: &StonePressurePlate,
	72: &WoodenPressurePlate,
	73: &RedstoneOre,
	76: &RedstoneTorch,
	77: &StoneButton,
	78: &SnowLayer,
	79: &Ice,
	80: &Snow,
	81: &Cactus,
	82: &Clay,
	84: &Jukebox,
	85: &Fence,
	86: &Pumpkin,
	87: &Netherrack,
	88: &SoulSand,
	89: &Glowstone,
	91: &LitPumpkin,
	95: &StainedGlass,
	96: &Trapdoor,
	97: &MonsterEgg,
	98: &Stonebrick,
	99: &BrownMushroomBlock,
	100: &RedMushroomBlock,
	101: &IronBars,
	102: &GlassPane,
	103: &MelonBlock,
	106: &Vine,
	107: &FenceGate,
	108: &BrickStairs,
	109: &StoneBrickStairs,
	110: &Mycelium,
	111: &Waterlily,
	112: &NetherBrick,
	113: &NetherBrickFence,
	114: &NetherBrickStairs,
	116: &EnchantingTable,
	120: &EndPortalFrame,
	121: &EndStone,
	122: &DragonEgg,
	123: &RedstoneLamp,
	126: &WoodenSlab,
	128: &SandstoneStairs,
	129: &EmeraldOre,
	130: &EnderChest,
	131: &TripwireHook,
	133: &EmeraldBlock,
	134: &SpruceStairs,
	135: &BirchStairs,
	136: &JungleStairs,
	137: &CommandBlock,
	138: &Beacon,
	139: &CobblestoneWall,
	143: &WoodenButton,
	145: &Anvil,
	146: &TrappedChest,
	147: &LightWeightedPressurePlate,
	148: &HeavyWeightedPressurePlate,
	151: &DaylightDetector,
	152: &RedstoneBlock,
	153: &QuartzOre,
	154: &Hopper,
	155: &QuartzBlock,
	156: &QuartzStairs,
	157: &ActivatorRail,
	158: &Dropper,
	159: &StainedHardenedClay,
	160: &StainedGlassPane,
	161: &Leaves2,
	162: &Log2,
	163: &AcaciaStairs,
	164: &DarkOakStairs,
	165: &Slime,
	166: &Barrier,
	167: &IronTrapdoor,
	168: &Prismarine,
	169: &SeaLantern,
	170: &HayBlock,
	171: &Carpet,
	172: &HardenedClay,
	173: &CoalBlock,
	174: &PackedIce,
	175: &DoublePlant,
	179: &RedSandstone,
	180: &RedSandstoneStairs,
	182: &StoneSlab2,
	183: &SpruceFenceGate,
	184: &BirchFenceGate,
	185: &JungleFenceGate,
	186: &DarkOakFenceGate,
	187: &AcaciaFenceGate,
	188: &SpruceFence,
	189: &BirchFence,
	190: &JungleFence,
	191: &DarkOakFence,
	192: &AcaciaFence,
	198: &EndRod,
	199: &ChorusPlant,
	200: &ChorusFlower,
	201: &PurpurBlock,
	202: &PurpurPillar,
	203: &PurpurStairs,
	205: &PurpurSlab,
	206: &EndBricks,
	208: &GrassPath,
	210: &RepeatingCommandBlock,
	211: &ChainCommandBlock,
	213: &Magma,
	214: &NetherWartBlock,
	215: &RedNetherBrick,
	216: &BoneBlock,
	217: &StructureVoid,
	218: &Observer,
	219: &WhiteShulkerBox,
	220: &OrangeShulkerBox,
	221: &MagentaShulkerBox,
	222: &LightBlueShulkerBox,
	223: &YellowShulkerBox,
	224: &LimeShulkerBox,
	225: &PinkShulkerBox,
	226: &GrayShulkerBox,
	227: &SilverShulkerBox,
	228: &CyanShulkerBox,
	229: &PurpleShulkerBox,
	230: &BlueShulkerBox,
	231: &BrownShulkerBox,
	232: &GreenShulkerBox,
	233: &RedShulkerBox,
	234: &BlackShulkerBox,
	235: &WhiteGlazedTerracotta,
	236: &OrangeGlazedTerracotta,
	237: &MagentaGlazedTerracotta,
	238: &LightBlueGlazedTerracotta,
	239: &YellowGlazedTerracotta,
	240: &LimeGlazedTerracotta,
	241: &PinkGlazedTerracotta,
	242: &GrayGlazedTerracotta,
	243: &SilverGlazedTerracotta,
	244: &CyanGlazedTerracotta,
	245: &PurpleGlazedTerracotta,
	246: &BlueGlazedTerracotta,
	247: &BrownGlazedTerracotta,
	248: &GreenGlazedTerracotta,
	249: &RedGlazedTerracotta,
	250: &BlackGlazedTerracotta,
	251: &Concrete,
	252: &ConcretePowder,
	255: &StructureBlock,
	256: &IronShovel,
	257: &IronPickaxe,
	258: &IronAxe,
	259: &FlintAndSteel,
	260: &Apple,
	261: &Bow,
	262: &Arrow,
	263: &Coal,
	264: &Diamond,
	265: &IronIngot,
	266: &GoldIngot,
	267: &IronSword,
	268: &WoodenSword,
	269: &WoodenShovel,
	270: &WoodenPickaxe,
	271: &WoodenAxe,
	272: &StoneSword,
	273: &StoneShovel,
	274: &StonePickaxe,
	275: &StoneAxe,
	276: &DiamondSword,
	277: &DiamondShovel,
	278: &DiamondPickaxe,
	279: &DiamondAxe,
	280: &Stick,
	281: &Bowl,
	282: &MushroomStew,
	283: &GoldenSword,
	284: &GoldenShovel,
	285: &GoldenPickaxe,
	286: &GoldenAxe,
	287: &String,
	288: &Feather,
	289: &Gunpowder,
	290: &WoodenHoe,
	291: &StoneHoe,
	292: &IronHoe,
	293: &DiamondHoe,
	294: &GoldenHoe,
	295: &WheatSeeds,
	296: &Wheat,
	297: &Bread,
	298: &LeatherHelmet,
	299: &LeatherChestplate,
	300: &LeatherLeggings,
	301: &LeatherBoots,
	302: &ChainmailHelmet,
	303: &ChainmailChestplate,
	304: &ChainmailLeggings,
	305: &ChainmailBoots,
	306: &IronHelmet,
	307: &IronChestplate,
	308: &IronLeggings,
	309: &IronBoots,
	310: &DiamondHelmet,
	311: &DiamondChestplate,
	312: &DiamondLeggings,
	313: &DiamondBoots,
	314: &GoldenHelmet,
	315: &GoldenChestplate,
	316: &GoldenLeggings,
	317: &GoldenBoots,
	318: &Flint,
	319: &Porkchop,
	320: &CookedPorkchop,
	321: &Painting,
	322: &GoldenApple,
	323: &Sign,
	324: &WoodenDoor,
	325: &Bucket,
	326: &WaterBucket,
	327: &LavaBucket,
	328: &Minecart,
	329: &Saddle,
	330: &IronDoor,
	331: &Redstone,
	332: &Snowball,
	333: &Boat,
	334: &Leather,
	335: &MilkBucket,
	336: &Brick,
	337: &ClayBall,
	338: &Reeds,
	339: &Paper,
	340: &Book,
	341: &SlimeBall,
	342: &ChestMinecart,
	343: &FurnaceMinecart,
	344: &Egg,
	345: &Compass,
	346: &FishingRod,
	347: &Clock,
	348: &GlowstoneDust,
	349: &Fish,
	350: &CookedFish,
	351: &Dye,
	352: &Bone,
	353: &Sugar,
	354: &Cake,
	355: &Bed,
	356: &Repeater,
	357: &Cookie,
	358: &FilledMap,
	359: &Shears,
	360: &Melon,
	361: &PumpkinSeeds,
	362: &MelonSeeds,
	363: &Beef,
	364: &CookedBeef,
	365: &Chicken,
	366: &CookedChicken,
	367: &RottenFlesh,
	368: &EnderPearl,
	369: &BlazeRod,
	370: &GhastTear,
	371: &GoldNugget,
	372: &NetherWart,
	373: &Potion,
	374: &GlassBottle,
	375: &SpiderEye,
	376: &FermentedSpiderEye,
	377: &BlazePowder,
	378: &MagmaCream,
	379: &BrewingStand,
	380: &Cauldron,
	381: &EnderEye,
	382: &SpeckledMelon,
	383: &SpawnEgg,
	384: &ExperienceBottle,
	385: &FireCharge,
	386: &WritableBook,
	387: &WrittenBook,
	388: &Emerald,
	389: &ItemFrame,
	390: &FlowerPot,
	391: &Carrot,
	392: &Potato,
	393: &BakedPotato,
	394: &PoisonousPotato,
	395: &Map,
	396: &GoldenCarrot,
	397: &Skull,
	398: &CarrotOnAStick,
	399: &NetherStar,
	400: &PumpkinPie,
	401: &Fireworks,
	402: &FireworkCharge,
	403: &EnchantedBook,
	404: &Comparator,
	405: &Netherbrick,
	406: &Quartz,
	407: &TntMinecart,
	408: &HopperMinecart,
	409: &PrismarineShard,
	410: &PrismarineCrystals,
	411: &Rabbit,
	412: &CookedRabbit,
	413: &RabbitStew,
	414: &RabbitFoot,
	415: &RabbitHide,
	416: &ArmorStand,
	417: &IronHorseArmor,
	418: &GoldenHorseArmor,
	419: &DiamondHorseArmor,
	420: &Lead,
	421: &NameTag,
	422: &CommandBlockMinecart,
	423: &Mutton,
	424: &CookedMutton,
	425: &Banner,
	426: &EndCrystal,
	427: &SpruceDoor,
	428: &BirchDoor,
	429: &JungleDoor,
	430: &AcaciaDoor,
	431: &DarkOakDoor,
	432: &ChorusFruit,
	433: &ChorusFruitPopped,
	434: &Beetroot,
	435: &BeetrootSeeds,
	436: &BeetrootSoup,
	437: &DragonBreath,
	438: &SplashPotion,
	439: &SpectralArrow,
	440: &TippedArrow,
	441: &LingeringPotion,
	442: &Shield,
	443: &Elytra,
	444: &SpruceBoat,
	445: &BirchBoat,
	446: &JungleBoat,
	447: &AcaciaBoat,
	448: &DarkOakBoat,
	449: &TotemOfUndying,
	450: &ShulkerShell,
	452: &IronNugget,
	453: &KnowledgeBook,
	2256: &Record13,
	2257: &RecordCat,
	2258: &RecordBlocks,
	2259: &RecordChirp,
	2260: &RecordFar,
	2261: &RecordMall,
	2262: &RecordMellohi,
	2263: &RecordStal,
	2264: &RecordStrad,
	2265: &RecordWard,
	2266: &Record11,
	2267: &RecordWait,
}