// Code generated by downloader.go; DO NOT EDIT.
package tl_ph

import "github.com/Tnze/go-mc/chat"

func init() { chat.SetLanguage(Map) }

var Map = map[string]string{"block.minecraft.sand": "Buhangin", "block.minecraft.water": "Agwa", "createWorld.customize.custom.preset.drought": "Baisi", "createWorld.customize.custom.preset.waterWorld": "Daigdig na Agwa", "createWorld.customize.custom.useCaves": "Mga Kuweba", "createWorld.customize.custom.useVillages": "Mga Balangay", "gui.no": "Hindi", "gui.yes": "Oo", "menu.disconnect": "Magkalag", "options.chat.width": "Kaluwangan", "options.modelPart.hat": "Sambalilo", "selectWorld.delete": "Kaltasin", "selectWorld.deleteButton": "Kaltasin", "selectWorld.edit": "Bumago", "selectWorld.empty": "basio", "selectWorld.world": "Daigdig"}
