// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var Activity = []string{
	"minecraft:core",
	"minecraft:idle",
	"minecraft:work",
	"minecraft:play",
	"minecraft:rest",
	"minecraft:meet",
	"minecraft:panic",
	"minecraft:raid",
	"minecraft:pre_raid",
	"minecraft:hide",
	"minecraft:fight",
	"minecraft:celebrate",
	"minecraft:admire_item",
	"minecraft:avoid",
	"minecraft:ride",
	"minecraft:play_dead",
	"minecraft:long_jump",
	"minecraft:ram",
	"minecraft:tongue",
	"minecraft:swim",
	"minecraft:lay_spawn",
	"minecraft:sniff",
	"minecraft:investigate",
	"minecraft:roar",
	"minecraft:emerge",
	"minecraft:dig",
}
