// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var ArmorMaterial = []string{
	"minecraft:leather",
	"minecraft:chainmail",
	"minecraft:iron",
	"minecraft:gold",
	"minecraft:diamond",
	"minecraft:turtle",
	"minecraft:netherite",
	"minecraft:armadillo",
}
