// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var CatVariant = []string{
	"minecraft:tabby",
	"minecraft:black",
	"minecraft:red",
	"minecraft:siamese",
	"minecraft:british_shorthair",
	"minecraft:calico",
	"minecraft:persian",
	"minecraft:ragdoll",
	"minecraft:white",
	"minecraft:jellie",
	"minecraft:all_black",
}
