// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var ChunkStatus = []string{
	"minecraft:empty",
	"minecraft:structure_starts",
	"minecraft:structure_references",
	"minecraft:biomes",
	"minecraft:noise",
	"minecraft:surface",
	"minecraft:carvers",
	"minecraft:features",
	"minecraft:initialize_light",
	"minecraft:light",
	"minecraft:spawn",
	"minecraft:full",
}
