// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var CreativeModeTab = []string{
	"minecraft:building_blocks",
	"minecraft:colored_blocks",
	"minecraft:natural_blocks",
	"minecraft:functional_blocks",
	"minecraft:redstone_blocks",
	"minecraft:hotbar",
	"minecraft:search",
	"minecraft:tools_and_utilities",
	"minecraft:combat",
	"minecraft:food_and_drinks",
	"minecraft:ingredients",
	"minecraft:spawn_eggs",
	"minecraft:op_blocks",
	"minecraft:inventory",
}
