// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var DecoratedPotPattern = []string{
	"minecraft:angler",
	"minecraft:archer",
	"minecraft:arms_up",
	"minecraft:blade",
	"minecraft:brewer",
	"minecraft:burn",
	"minecraft:danger",
	"minecraft:explorer",
	"minecraft:flow",
	"minecraft:friend",
	"minecraft:guster",
	"minecraft:heart",
	"minecraft:heartbreak",
	"minecraft:howl",
	"minecraft:miner",
	"minecraft:mourner",
	"minecraft:plenty",
	"minecraft:prize",
	"minecraft:scrape",
	"minecraft:sheaf",
	"minecraft:shelter",
	"minecraft:skull",
	"minecraft:snort",
	"minecraft:blank",
}
