// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var EnchantmentLevelBasedValueType = []string{
	"minecraft:clamped",
	"minecraft:fraction",
	"minecraft:levels_squared",
	"minecraft:linear",
	"minecraft:lookup",
}
