// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var EnchantmentValueEffectType = []string{
	"minecraft:add",
	"minecraft:all_of",
	"minecraft:multiply",
	"minecraft:remove_binomial",
	"minecraft:set",
}
