// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var EnchantmentProviderType = []string{
	"minecraft:by_cost",
	"minecraft:by_cost_with_difficulty",
	"minecraft:single",
}
