// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var EnchantmentLocationBasedEffectType = []string{
	"minecraft:all_of",
	"minecraft:apply_mob_effect",
	"minecraft:attribute",
	"minecraft:damage_entity",
	"minecraft:damage_item",
	"minecraft:explode",
	"minecraft:ignite",
	"minecraft:play_sound",
	"minecraft:replace_block",
	"minecraft:replace_disk",
	"minecraft:run_function",
	"minecraft:set_block_properties",
	"minecraft:spawn_particles",
	"minecraft:summon_entity",
}
