// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var EntitySubPredicateType = []string{
	"minecraft:lightning",
	"minecraft:fishing_hook",
	"minecraft:player",
	"minecraft:slime",
	"minecraft:raider",
	"minecraft:axolotl",
	"minecraft:boat",
	"minecraft:fox",
	"minecraft:mooshroom",
	"minecraft:rabbit",
	"minecraft:horse",
	"minecraft:llama",
	"minecraft:villager",
	"minecraft:parrot",
	"minecraft:tropical_fish",
	"minecraft:painting",
	"minecraft:cat",
	"minecraft:frog",
	"minecraft:wolf",
}
