// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var FloatProviderType = []string{
	"minecraft:constant",
	"minecraft:uniform",
	"minecraft:clamped_normal",
	"minecraft:trapezoid",
}
