// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var Fluid = []string{
	"minecraft:empty",
	"minecraft:flowing_water",
	"minecraft:water",
	"minecraft:flowing_lava",
	"minecraft:lava",
}
