// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var HeightProviderType = []string{
	"minecraft:constant",
	"minecraft:uniform",
	"minecraft:biased_to_bottom",
	"minecraft:very_biased_to_bottom",
	"minecraft:trapezoid",
	"minecraft:weighted_list",
}
