// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var IntProviderType = []string{
	"minecraft:constant",
	"minecraft:uniform",
	"minecraft:biased_to_bottom",
	"minecraft:clamped",
	"minecraft:weighted_list",
	"minecraft:clamped_normal",
}
