// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var ItemSubPredicateType = []string{
	"minecraft:damage",
	"minecraft:enchantments",
	"minecraft:stored_enchantments",
	"minecraft:potion_contents",
	"minecraft:custom_data",
	"minecraft:container",
	"minecraft:bundle_contents",
	"minecraft:firework_explosion",
	"minecraft:fireworks",
	"minecraft:writable_book_content",
	"minecraft:written_book_content",
	"minecraft:attribute_modifiers",
	"minecraft:trim",
	"minecraft:jukebox_playable",
}
