// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var LootNumberProviderType = []string{
	"minecraft:constant",
	"minecraft:uniform",
	"minecraft:binomial",
	"minecraft:score",
	"minecraft:storage",
	"minecraft:enchantment_level",
}
