// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var LootPoolEntryType = []string{
	"minecraft:empty",
	"minecraft:item",
	"minecraft:loot_table",
	"minecraft:dynamic",
	"minecraft:tag",
	"minecraft:alternatives",
	"minecraft:sequence",
	"minecraft:group",
}
