// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var LootConditionType = []string{
	"minecraft:inverted",
	"minecraft:any_of",
	"minecraft:all_of",
	"minecraft:random_chance",
	"minecraft:random_chance_with_enchanted_bonus",
	"minecraft:entity_properties",
	"minecraft:killed_by_player",
	"minecraft:entity_scores",
	"minecraft:block_state_property",
	"minecraft:match_tool",
	"minecraft:table_bonus",
	"minecraft:survives_explosion",
	"minecraft:damage_source_properties",
	"minecraft:location_check",
	"minecraft:weather_check",
	"minecraft:reference",
	"minecraft:time_check",
	"minecraft:value_check",
	"minecraft:enchantment_active_check",
}
