// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var Menu = []string{
	"minecraft:generic_9x1",
	"minecraft:generic_9x2",
	"minecraft:generic_9x3",
	"minecraft:generic_9x4",
	"minecraft:generic_9x5",
	"minecraft:generic_9x6",
	"minecraft:generic_3x3",
	"minecraft:crafter_3x3",
	"minecraft:anvil",
	"minecraft:beacon",
	"minecraft:blast_furnace",
	"minecraft:brewing_stand",
	"minecraft:crafting",
	"minecraft:enchantment",
	"minecraft:furnace",
	"minecraft:grindstone",
	"minecraft:hopper",
	"minecraft:lectern",
	"minecraft:loom",
	"minecraft:merchant",
	"minecraft:shulker_box",
	"minecraft:smithing",
	"minecraft:smoker",
	"minecraft:cartography_table",
	"minecraft:stonecutter",
}
