// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var PointOfInterestType = []string{
	"minecraft:armorer",
	"minecraft:butcher",
	"minecraft:cartographer",
	"minecraft:cleric",
	"minecraft:farmer",
	"minecraft:fisherman",
	"minecraft:fletcher",
	"minecraft:leatherworker",
	"minecraft:librarian",
	"minecraft:mason",
	"minecraft:shepherd",
	"minecraft:toolsmith",
	"minecraft:weaponsmith",
	"minecraft:home",
	"minecraft:meeting",
	"minecraft:beehive",
	"minecraft:bee_nest",
	"minecraft:nether_portal",
	"minecraft:lodestone",
	"minecraft:lightning_rod",
}
