// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var PosRuleTest = []string{
	"minecraft:always_true",
	"minecraft:linear_pos",
	"minecraft:axis_aligned_linear_pos",
}
