// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var RecipeSerializer = []string{
	"minecraft:crafting_shaped",
	"minecraft:crafting_shapeless",
	"minecraft:crafting_special_armordye",
	"minecraft:crafting_special_bookcloning",
	"minecraft:crafting_special_mapcloning",
	"minecraft:crafting_special_mapextending",
	"minecraft:crafting_special_firework_rocket",
	"minecraft:crafting_special_firework_star",
	"minecraft:crafting_special_firework_star_fade",
	"minecraft:crafting_special_tippedarrow",
	"minecraft:crafting_special_bannerduplicate",
	"minecraft:crafting_special_shielddecoration",
	"minecraft:crafting_special_shulkerboxcoloring",
	"minecraft:crafting_special_suspiciousstew",
	"minecraft:crafting_special_repairitem",
	"minecraft:smelting",
	"minecraft:blasting",
	"minecraft:smoking",
	"minecraft:campfire_cooking",
	"minecraft:stonecutting",
	"minecraft:smithing_transform",
	"minecraft:smithing_trim",
	"minecraft:crafting_decorated_pot",
}
