// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var RecipeType = []string{
	"minecraft:crafting",
	"minecraft:smelting",
	"minecraft:blasting",
	"minecraft:smoking",
	"minecraft:campfire_cooking",
	"minecraft:stonecutting",
	"minecraft:smithing",
}
