// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var RuleBlockEntityModifier = []string{
	"minecraft:clear",
	"minecraft:passthrough",
	"minecraft:append_static",
	"minecraft:append_loot",
}
