// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var Schedule = []string{
	"minecraft:empty",
	"minecraft:simple",
	"minecraft:villager_baby",
	"minecraft:villager_default",
}
