// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var StatType = []string{
	"minecraft:mined",
	"minecraft:crafted",
	"minecraft:used",
	"minecraft:broken",
	"minecraft:picked_up",
	"minecraft:dropped",
	"minecraft:killed",
	"minecraft:killed_by",
	"minecraft:custom",
}
