// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var VillagerType = []string{
	"minecraft:desert",
	"minecraft:jungle",
	"minecraft:plains",
	"minecraft:savanna",
	"minecraft:snow",
	"minecraft:swamp",
	"minecraft:taiga",
}
