// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var VillagerProfession = []string{
	"minecraft:none",
	"minecraft:armorer",
	"minecraft:butcher",
	"minecraft:cartographer",
	"minecraft:cleric",
	"minecraft:farmer",
	"minecraft:fisherman",
	"minecraft:fletcher",
	"minecraft:leatherworker",
	"minecraft:librarian",
	"minecraft:mason",
	"minecraft:nitwit",
	"minecraft:shepherd",
	"minecraft:toolsmith",
	"minecraft:weaponsmith",
}
