// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var WorldgenTreeDecoratorType = []string{
	"minecraft:trunk_vine",
	"minecraft:leave_vine",
	"minecraft:cocoa",
	"minecraft:beehive",
	"minecraft:alter_ground",
	"minecraft:attached_to_leaves",
}
