// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var WorldgenTrunkPlacerType = []string{
	"minecraft:straight_trunk_placer",
	"minecraft:forking_trunk_placer",
	"minecraft:giant_trunk_placer",
	"minecraft:mega_jungle_trunk_placer",
	"minecraft:dark_oak_trunk_placer",
	"minecraft:fancy_trunk_placer",
	"minecraft:bending_trunk_placer",
	"minecraft:upwards_branching_trunk_placer",
	"minecraft:cherry_trunk_placer",
}
