// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var WorldgenFeatureSizeType = []string{
	"minecraft:two_layers_feature_size",
	"minecraft:three_layers_feature_size",
}
