// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var WorldgenStructureType = []string{
	"minecraft:buried_treasure",
	"minecraft:desert_pyramid",
	"minecraft:end_city",
	"minecraft:fortress",
	"minecraft:igloo",
	"minecraft:jigsaw",
	"minecraft:jungle_temple",
	"minecraft:mineshaft",
	"minecraft:nether_fossil",
	"minecraft:ocean_monument",
	"minecraft:ocean_ruin",
	"minecraft:ruined_portal",
	"minecraft:shipwreck",
	"minecraft:stronghold",
	"minecraft:swamp_hut",
	"minecraft:woodland_mansion",
}
