// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var WorldgenPlacementModifierType = []string{
	"minecraft:block_predicate_filter",
	"minecraft:rarity_filter",
	"minecraft:surface_relative_threshold_filter",
	"minecraft:surface_water_depth_filter",
	"minecraft:biome",
	"minecraft:count",
	"minecraft:noise_based_count",
	"minecraft:noise_threshold_count",
	"minecraft:count_on_every_layer",
	"minecraft:environment_scan",
	"minecraft:heightmap",
	"minecraft:height_range",
	"minecraft:in_square",
	"minecraft:random_offset",
	"minecraft:carving_mask",
	"minecraft:fixed_placement",
}
