// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var WorldgenStructureProcessor = []string{
	"minecraft:block_ignore",
	"minecraft:block_rot",
	"minecraft:gravity",
	"minecraft:jigsaw_replacement",
	"minecraft:rule",
	"minecraft:nop",
	"minecraft:block_age",
	"minecraft:blackstone_replace",
	"minecraft:lava_submerged_block",
	"minecraft:protected_blocks",
	"minecraft:capped",
}
