// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var WorldgenMaterialCondition = []string{
	"minecraft:biome",
	"minecraft:noise_threshold",
	"minecraft:vertical_gradient",
	"minecraft:y_above",
	"minecraft:water",
	"minecraft:temperature",
	"minecraft:steep",
	"minecraft:not",
	"minecraft:hole",
	"minecraft:above_preliminary_surface",
	"minecraft:stone_depth",
}
