// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var WorldgenMaterialRule = []string{
	"minecraft:bandlands",
	"minecraft:block",
	"minecraft:sequence",
	"minecraft:condition",
}
