// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var WorldgenBiomeSource = []string{
	"minecraft:fixed",
	"minecraft:multi_noise",
	"minecraft:checkerboard",
	"minecraft:the_end",
}
