// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var WorldgenFoliagePlacerType = []string{
	"minecraft:blob_foliage_placer",
	"minecraft:spruce_foliage_placer",
	"minecraft:pine_foliage_placer",
	"minecraft:acacia_foliage_placer",
	"minecraft:bush_foliage_placer",
	"minecraft:fancy_foliage_placer",
	"minecraft:jungle_foliage_placer",
	"minecraft:mega_pine_foliage_placer",
	"minecraft:dark_oak_foliage_placer",
	"minecraft:random_spread_foliage_placer",
	"minecraft:cherry_foliage_placer",
}
