// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var WorldgenStructurePoolElement = []string{
	"minecraft:single_pool_element",
	"minecraft:list_pool_element",
	"minecraft:feature_pool_element",
	"minecraft:empty_pool_element",
	"minecraft:legacy_single_pool_element",
}
