// This file is automatically generated by gen_packetIDs.go. DO NOT EDIT.

package packetid

// Login state
const (
	// Clientbound
	Disconnect                 = 0x0
	EncryptionBeginClientbound = 0x1
	Success                    = 0x2
	Compress                   = 0x3
	LoginPluginRequest         = 0x4

	// Serverbound
	LoginStart                 = 0x0
	EncryptionBeginServerbound = 0x1
	LoginPluginResponse        = 0x2
)

// Ping state
const (
	// Clientbound
	ServerInfo      = 0x0
	PingClientbound = 0x1

	// Serverbound
	PingStart       = 0x0
	PingServerbound = 0x1
)

// Play state
const (
	// Clientbound
	SpawnEntity                = 0x0
	SpawnEntityExperienceOrb   = 0x1
	SpawnEntityLiving          = 0x2
	SpawnEntityPainting        = 0x3
	NamedEntitySpawn           = 0x4
	Animation                  = 0x5
	Statistics                 = 0x6
	AcknowledgePlayerDigging   = 0x7
	BlockBreakAnimation        = 0x8
	TileEntityData             = 0x9
	BlockAction                = 0xa
	BlockChange                = 0xb
	BossBar                    = 0xc
	Difficulty                 = 0xd
	ChatClientbound            = 0xe
	TabCompleteClientbound     = 0xf
	DeclareCommands            = 0x10
	TransactionClientbound     = 0x11
	CloseWindowClientbound     = 0x12
	WindowItems                = 0x13
	CraftProgressBar           = 0x14
	SetSlot                    = 0x15
	SetCooldown                = 0x16
	CustomPayloadClientbound   = 0x17
	NamedSoundEffect           = 0x18
	KickDisconnect             = 0x19
	EntityStatus               = 0x1a
	Explosion                  = 0x1b
	UnloadChunk                = 0x1c
	GameStateChange            = 0x1d
	OpenHorseWindow            = 0x1e
	KeepAliveClientbound       = 0x1f
	MapChunk                   = 0x20
	WorldEvent                 = 0x21
	WorldParticles             = 0x22
	UpdateLight                = 0x23
	Login                      = 0x24
	Map                        = 0x25
	TradeList                  = 0x26
	RelEntityMove              = 0x27
	EntityMoveLook             = 0x28
	EntityLook                 = 0x29
	Entity                     = 0x2a
	VehicleMoveClientbound     = 0x2b
	OpenBook                   = 0x2c
	OpenWindow                 = 0x2d
	OpenSignEntity             = 0x2e
	CraftRecipeResponse        = 0x2f
	AbilitiesClientbound       = 0x30
	CombatEvent                = 0x31
	PlayerInfo                 = 0x32
	FacePlayer                 = 0x33
	PositionClientbound        = 0x34
	UnlockRecipes              = 0x35
	EntityDestroy              = 0x36
	RemoveEntityEffect         = 0x37
	ResourcePackSend           = 0x38
	Respawn                    = 0x39
	EntityHeadRotation         = 0x3a
	MultiBlockChange           = 0x3b
	SelectAdvancementTab       = 0x3c
	WorldBorder                = 0x3d
	Camera                     = 0x3e
	HeldItemSlotClientbound    = 0x3f
	UpdateViewPosition         = 0x40
	UpdateViewDistance         = 0x41
	SpawnPosition              = 0x42
	ScoreboardDisplayObjective = 0x43
	EntityMetadata             = 0x44
	AttachEntity               = 0x45
	EntityVelocity             = 0x46
	EntityEquipment            = 0x47
	Experience                 = 0x48
	UpdateHealth               = 0x49
	ScoreboardObjective        = 0x4a
	SetPassengers              = 0x4b
	Teams                      = 0x4c
	ScoreboardScore            = 0x4d
	UpdateTime                 = 0x4e
	Title                      = 0x4f
	EntitySoundEffect          = 0x50
	SoundEffect                = 0x51
	StopSound                  = 0x52
	PlayerlistHeader           = 0x53
	NbtQueryResponse           = 0x54
	Collect                    = 0x55
	EntityTeleport             = 0x56
	Advancements               = 0x57
	EntityUpdateAttributes     = 0x58
	EntityEffect               = 0x59
	DeclareRecipes             = 0x5a
	Tags                       = 0x5b

	// Serverbound
	TeleportConfirm            = 0x0
	QueryBlockNbt              = 0x1
	SetDifficulty              = 0x2
	ChatServerbound            = 0x3
	ClientCommand              = 0x4
	Settings                   = 0x5
	TabCompleteServerbound     = 0x6
	TransactionServerbound     = 0x7
	EnchantItem                = 0x8
	WindowClick                = 0x9
	CloseWindowServerbound     = 0xa
	CustomPayloadServerbound   = 0xb
	EditBook                   = 0xc
	QueryEntityNbt             = 0xd
	UseEntity                  = 0xe
	GenerateStructure          = 0xf
	KeepAliveServerbound       = 0x10
	LockDifficulty             = 0x11
	PositionServerbound        = 0x12
	PositionLook               = 0x13
	Look                       = 0x14
	Flying                     = 0x15
	VehicleMoveServerbound     = 0x16
	SteerBoat                  = 0x17
	PickItem                   = 0x18
	CraftRecipeRequest         = 0x19
	AbilitiesServerbound       = 0x1a
	BlockDig                   = 0x1b
	EntityAction               = 0x1c
	SteerVehicle               = 0x1d
	DisplayedRecipe            = 0x1e
	RecipeBook                 = 0x1f
	NameItem                   = 0x20
	ResourcePackReceive        = 0x21
	AdvancementTab             = 0x22
	SelectTrade                = 0x23
	SetBeaconEffect            = 0x24
	HeldItemSlotServerbound    = 0x25
	UpdateCommandBlock         = 0x26
	UpdateCommandBlockMinecart = 0x27
	SetCreativeSlot            = 0x28
	UpdateJigsawBlock          = 0x29
	UpdateStructureBlock       = 0x2a
	UpdateSign                 = 0x2b
	ArmAnimation               = 0x2c
	Spectate                   = 0x2d
	BlockPlace                 = 0x2e
	UseItem                    = 0x2f
)
