// Code generated by "stringer -type ServerboundPacketID"; DO NOT EDIT.

package packetid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerboundAcceptTeleportation-0]
	_ = x[ServerboundBlockEntityTagQuery-1]
	_ = x[ServerboundChangeDifficulty-2]
	_ = x[ServerboundChatAck-3]
	_ = x[ServerboundChatCommand-4]
	_ = x[ServerboundChat-5]
	_ = x[ServerboundChatSessionUpdate-6]
	_ = x[ServerboundChunkBatchReceived-7]
	_ = x[ServerboundClientCommand-8]
	_ = x[ServerboundClientInformation-9]
	_ = x[ServerboundCommandSuggestion-10]
	_ = x[ServerboundConfigurationAcknowledged-11]
	_ = x[ServerboundContainerButtonClick-12]
	_ = x[ServerboundContainerClick-13]
	_ = x[ServerboundContainerClose-14]
	_ = x[ServerboundCustomPayload-15]
	_ = x[ServerboundEditBook-16]
	_ = x[ServerboundEntityTagQuery-17]
	_ = x[ServerboundInteract-18]
	_ = x[ServerboundJigsawGenerate-19]
	_ = x[ServerboundKeepAlive-20]
	_ = x[ServerboundLockDifficulty-21]
	_ = x[ServerboundMovePlayerPos-22]
	_ = x[ServerboundMovePlayerPosRot-23]
	_ = x[ServerboundMovePlayerRot-24]
	_ = x[ServerboundMovePlayerStatusOnly-25]
	_ = x[ServerboundMoveVehicle-26]
	_ = x[ServerboundPaddleBoat-27]
	_ = x[ServerboundPickItem-28]
	_ = x[ServerboundPingRequest-29]
	_ = x[ServerboundPlaceRecipe-30]
	_ = x[ServerboundPlayerAbilities-31]
	_ = x[ServerboundPlayerAction-32]
	_ = x[ServerboundPlayerCommand-33]
	_ = x[ServerboundPlayerInput-34]
	_ = x[ServerboundPong-35]
	_ = x[ServerboundRecipeBookChangeSettings-36]
	_ = x[ServerboundRecipeBookSeenRecipe-37]
	_ = x[ServerboundRenameItem-38]
	_ = x[ServerboundResourcePack-39]
	_ = x[ServerboundSeenAdvancements-40]
	_ = x[ServerboundSelectTrade-41]
	_ = x[ServerboundSetBeacon-42]
	_ = x[ServerboundSetCarriedItem-43]
	_ = x[ServerboundSetCommandBlock-44]
	_ = x[ServerboundSetCommandMinecart-45]
	_ = x[ServerboundSetCreativeModeSlot-46]
	_ = x[ServerboundSetJigsawBlock-47]
	_ = x[ServerboundSetStructureBlock-48]
	_ = x[ServerboundSignUpdate-49]
	_ = x[ServerboundSwing-50]
	_ = x[ServerboundTeleportToEntity-51]
	_ = x[ServerboundUseItemOn-52]
	_ = x[ServerboundUseItem-53]
}

const _ServerboundPacketID_name = "ServerboundAcceptTeleportationServerboundBlockEntityTagQueryServerboundChangeDifficultyServerboundChatAckServerboundChatCommandServerboundChatServerboundChatSessionUpdateServerboundChunkBatchReceivedServerboundClientCommandServerboundClientInformationServerboundCommandSuggestionServerboundConfigurationAcknowledgedServerboundContainerButtonClickServerboundContainerClickServerboundContainerCloseServerboundCustomPayloadServerboundEditBookServerboundEntityTagQueryServerboundInteractServerboundJigsawGenerateServerboundKeepAliveServerboundLockDifficultyServerboundMovePlayerPosServerboundMovePlayerPosRotServerboundMovePlayerRotServerboundMovePlayerStatusOnlyServerboundMoveVehicleServerboundPaddleBoatServerboundPickItemServerboundPingRequestServerboundPlaceRecipeServerboundPlayerAbilitiesServerboundPlayerActionServerboundPlayerCommandServerboundPlayerInputServerboundPongServerboundRecipeBookChangeSettingsServerboundRecipeBookSeenRecipeServerboundRenameItemServerboundResourcePackServerboundSeenAdvancementsServerboundSelectTradeServerboundSetBeaconServerboundSetCarriedItemServerboundSetCommandBlockServerboundSetCommandMinecartServerboundSetCreativeModeSlotServerboundSetJigsawBlockServerboundSetStructureBlockServerboundSignUpdateServerboundSwingServerboundTeleportToEntityServerboundUseItemOnServerboundUseItem"

var _ServerboundPacketID_index = [...]uint16{0, 30, 60, 87, 105, 127, 142, 170, 199, 223, 251, 279, 315, 346, 371, 396, 420, 439, 464, 483, 508, 528, 553, 577, 604, 628, 659, 681, 702, 721, 743, 765, 791, 814, 838, 860, 875, 910, 941, 962, 985, 1012, 1034, 1054, 1079, 1105, 1134, 1164, 1189, 1217, 1238, 1254, 1281, 1301, 1319}

func (i ServerboundPacketID) String() string {
	if i < 0 || i >= ServerboundPacketID(len(_ServerboundPacketID_index)-1) {
		return "ServerboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerboundPacketID_name[_ServerboundPacketID_index[i]:_ServerboundPacketID_index[i+1]]
}
