// Code generated by "stringer -type ServerboundPacketID"; DO NOT EDIT.

package packetid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerboundLoginStart-0]
	_ = x[ServerboundLoginEncryptionResponse-1]
	_ = x[ServerboundLoginPluginResponse-2]
	_ = x[ServerboundLoginAcknowledged-3]
	_ = x[ServerboundStatusRequest-0]
	_ = x[ServerboundStatusPingRequest-1]
	_ = x[ServerboundConfigClientInformation-0]
	_ = x[ServerboundConfigCustomPayload-1]
	_ = x[ServerboundConfigFinishConfiguration-2]
	_ = x[ServerboundConfigKeepAlive-3]
	_ = x[ServerboundConfigPong-4]
	_ = x[ServerboundConfigResourcePack-5]
	_ = x[ServerboundAcceptTeleportation-0]
	_ = x[ServerboundBlockEntityTagQuery-1]
	_ = x[ServerboundChangeDifficulty-2]
	_ = x[ServerboundChatAck-3]
	_ = x[ServerboundChatCommand-4]
	_ = x[ServerboundChat-5]
	_ = x[ServerboundChatSessionUpdate-6]
	_ = x[ServerboundChunkBatchReceived-7]
	_ = x[ServerboundClientCommand-8]
	_ = x[ServerboundClientInformation-9]
	_ = x[ServerboundCommandSuggestion-10]
	_ = x[ServerboundConfigurationAcknowledged-11]
	_ = x[ServerboundContainerButtonClick-12]
	_ = x[ServerboundContainerClick-13]
	_ = x[ServerboundContainerClose-14]
	_ = x[ServerboundContainerSlotStateChanged-15]
	_ = x[ServerboundCustomPayload-16]
	_ = x[ServerboundEditBook-17]
	_ = x[ServerboundEntityTagQuery-18]
	_ = x[ServerboundInteract-19]
	_ = x[ServerboundJigsawGenerate-20]
	_ = x[ServerboundKeepAlive-21]
	_ = x[ServerboundLockDifficulty-22]
	_ = x[ServerboundMovePlayerPos-23]
	_ = x[ServerboundMovePlayerPosRot-24]
	_ = x[ServerboundMovePlayerRot-25]
	_ = x[ServerboundMovePlayerStatusOnly-26]
	_ = x[ServerboundMoveVehicle-27]
	_ = x[ServerboundPaddleBoat-28]
	_ = x[ServerboundPickItem-29]
	_ = x[ServerboundPingRequest-30]
	_ = x[ServerboundPlaceRecipe-31]
	_ = x[ServerboundPlayerAbilities-32]
	_ = x[ServerboundPlayerAction-33]
	_ = x[ServerboundPlayerCommand-34]
	_ = x[ServerboundPlayerInput-35]
	_ = x[ServerboundPong-36]
	_ = x[ServerboundRecipeBookChangeSettings-37]
	_ = x[ServerboundRecipeBookSeenRecipe-38]
	_ = x[ServerboundRenameItem-39]
	_ = x[ServerboundResourcePack-40]
	_ = x[ServerboundSeenAdvancements-41]
	_ = x[ServerboundSelectTrade-42]
	_ = x[ServerboundSetBeacon-43]
	_ = x[ServerboundSetCarriedItem-44]
	_ = x[ServerboundSetCommandBlock-45]
	_ = x[ServerboundSetCommandMinecart-46]
	_ = x[ServerboundSetCreativeModeSlot-47]
	_ = x[ServerboundSetJigsawBlock-48]
	_ = x[ServerboundSetStructureBlock-49]
	_ = x[ServerboundSignUpdate-50]
	_ = x[ServerboundSwing-51]
	_ = x[ServerboundTeleportToEntity-52]
	_ = x[ServerboundUseItemOn-53]
	_ = x[ServerboundUseItem-54]
}

const _ServerboundPacketID_name = "ServerboundLoginStartServerboundLoginEncryptionResponseServerboundLoginPluginResponseServerboundLoginAcknowledgedServerboundConfigPongServerboundConfigResourcePackServerboundChatSessionUpdateServerboundChunkBatchReceivedServerboundClientCommandServerboundClientInformationServerboundCommandSuggestionServerboundConfigurationAcknowledgedServerboundContainerButtonClickServerboundContainerClickServerboundContainerCloseServerboundContainerSlotStateChangedServerboundCustomPayloadServerboundEditBookServerboundEntityTagQueryServerboundInteractServerboundJigsawGenerateServerboundKeepAliveServerboundLockDifficultyServerboundMovePlayerPosServerboundMovePlayerPosRotServerboundMovePlayerRotServerboundMovePlayerStatusOnlyServerboundMoveVehicleServerboundPaddleBoatServerboundPickItemServerboundPingRequestServerboundPlaceRecipeServerboundPlayerAbilitiesServerboundPlayerActionServerboundPlayerCommandServerboundPlayerInputServerboundPongServerboundRecipeBookChangeSettingsServerboundRecipeBookSeenRecipeServerboundRenameItemServerboundResourcePackServerboundSeenAdvancementsServerboundSelectTradeServerboundSetBeaconServerboundSetCarriedItemServerboundSetCommandBlockServerboundSetCommandMinecartServerboundSetCreativeModeSlotServerboundSetJigsawBlockServerboundSetStructureBlockServerboundSignUpdateServerboundSwingServerboundTeleportToEntityServerboundUseItemOnServerboundUseItem"

var _ServerboundPacketID_index = [...]uint16{0, 21, 55, 85, 113, 134, 163, 191, 220, 244, 272, 300, 336, 367, 392, 417, 453, 477, 496, 521, 540, 565, 585, 610, 634, 661, 685, 716, 738, 759, 778, 800, 822, 848, 871, 895, 917, 932, 967, 998, 1019, 1042, 1069, 1091, 1111, 1136, 1162, 1191, 1221, 1246, 1274, 1295, 1311, 1338, 1358, 1376}

func (i ServerboundPacketID) String() string {
	if i < 0 || i >= ServerboundPacketID(len(_ServerboundPacketID_index)-1) {
		return "ServerboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerboundPacketID_name[_ServerboundPacketID_index[i]:_ServerboundPacketID_index[i+1]]
}
