// Code generated by gen_instruments.go DO NOT EDIT.
// Package instruments stores information about instruments in Minecraft.
package instruments

// ID describes the numeric ID of an instrument.
type ID uint32

// Instrument describes information about a type of instrument.
type Instrument struct {
	ID   ID
	Name string
}

var (
	Harp = Instrument{
		ID:   0,
		Name: "harp",
	}
	Basedrum = Instrument{
		ID:   1,
		Name: "basedrum",
	}
	Snare = Instrument{
		ID:   2,
		Name: "snare",
	}
	Hat = Instrument{
		ID:   3,
		Name: "hat",
	}
	Bass = Instrument{
		ID:   4,
		Name: "bass",
	}
	Flute = Instrument{
		ID:   5,
		Name: "flute",
	}
	Bell = Instrument{
		ID:   6,
		Name: "bell",
	}
	Guitar = Instrument{
		ID:   7,
		Name: "guitar",
	}
	Chime = Instrument{
		ID:   8,
		Name: "chime",
	}
	Xylophone = Instrument{
		ID:   9,
		Name: "xylophone",
	}
	IronXylophone = Instrument{
		ID:   10,
		Name: "iron_xylophone",
	}
	CowBell = Instrument{
		ID:   11,
		Name: "cow_bell",
	}
	Didgeridoo = Instrument{
		ID:   12,
		Name: "didgeridoo",
	}
	Bit = Instrument{
		ID:   13,
		Name: "bit",
	}
	Banjo = Instrument{
		ID:   14,
		Name: "banjo",
	}
	Pling = Instrument{
		ID:   15,
		Name: "pling",
	}
)

// ByID is an index of minecraft instruments by their ID.
var ByID = map[ID]*Instrument{
	0:  &Harp,
	1:  &Basedrum,
	2:  &Snare,
	3:  &Hat,
	4:  &Bass,
	5:  &Flute,
	6:  &Bell,
	7:  &Guitar,
	8:  &Chime,
	9:  &Xylophone,
	10: &IronXylophone,
	11: &CowBell,
	12: &Didgeridoo,
	13: &Bit,
	14: &Banjo,
	15: &Pling,
}

// ByName is an index of minecraft instruments by their name.
var ByName = map[string]*Instrument{
	"harp":           &Harp,
	"basedrum":       &Basedrum,
	"snare":          &Snare,
	"hat":            &Hat,
	"bass":           &Bass,
	"flute":          &Flute,
	"bell":           &Bell,
	"guitar":         &Guitar,
	"chime":          &Chime,
	"xylophone":      &Xylophone,
	"iron_xylophone": &IronXylophone,
	"cow_bell":       &CowBell,
	"didgeridoo":     &Didgeridoo,
	"bit":            &Bit,
	"banjo":          &Banjo,
	"pling":          &Pling,
}
