// Code generated by "stringer -type=AttachFace -output=attach_face_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttachFaceFloor-0]
	_ = x[AttachFaceWall-1]
	_ = x[AttachFaceCeiling-2]
}

const _AttachFace_name = "AttachFaceFloorAttachFaceWallAttachFaceCeiling"

var _AttachFace_index = [...]uint8{0, 15, 29, 46}

func (i AttachFace) String() string {
	if i >= AttachFace(len(_AttachFace_index)-1) {
		return "AttachFace(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AttachFace_name[_AttachFace_index[i]:_AttachFace_index[i+1]]
}

func (i AttachFace) Value() byte {
	return byte(i)
}
