// Code generated by "stringer -type=BambooLeaves -output=bamboo_leaves_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BambooLeavesNone-0]
	_ = x[BambooLeavesSmall-1]
	_ = x[BambooLeavesLarge-2]
}

const _BambooLeaves_name = "BambooLeavesNoneBambooLeavesSmallBambooLeavesLarge"

var _BambooLeaves_index = [...]uint8{0, 16, 33, 50}

func (i BambooLeaves) String() string {
	if i >= BambooLeaves(len(_BambooLeaves_index)-1) {
		return "BambooLeaves(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BambooLeaves_name[_BambooLeaves_index[i]:_BambooLeaves_index[i+1]]
}

func (i BambooLeaves) Value() byte {
	return byte(i)
}
