// Code generated by "stringer -type=BedPart -output=bed_part_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BedPartHead-0]
	_ = x[BedPartFoot-1]
}

const _BedPart_name = "BedPartHeadBedPartFoot"

var _BedPart_index = [...]uint8{0, 11, 22}

func (i BedPart) String() string {
	if i >= BedPart(len(_BedPart_index)-1) {
		return "BedPart(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BedPart_name[_BedPart_index[i]:_BedPart_index[i+1]]
}

func (i BedPart) Value() byte {
	return byte(i)
}
