// Code generated by "stringer -type=ChestType -output=chest_type_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChestTypeSingle-0]
	_ = x[ChestTypeLeft-1]
	_ = x[ChestTypeRight-2]
}

const _ChestType_name = "ChestTypeSingleChestTypeLeftChestTypeRight"

var _ChestType_index = [...]uint8{0, 15, 28, 42}

func (i ChestType) String() string {
	if i >= ChestType(len(_ChestType_index)-1) {
		return "ChestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChestType_name[_ChestType_index[i]:_ChestType_index[i+1]]
}

func (i ChestType) Value() byte {
	return byte(i)
}
