// Code generated by "stringer -type=ComparatorMode -output=comparator_mode_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComparatorModeCompare-0]
	_ = x[ComparatorModeSubtract-1]
}

const _ComparatorMode_name = "ComparatorModeCompareComparatorModeSubtract"

var _ComparatorMode_index = [...]uint8{0, 21, 43}

func (i ComparatorMode) String() string {
	if i >= ComparatorMode(len(_ComparatorMode_index)-1) {
		return "ComparatorMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComparatorMode_name[_ComparatorMode_index[i]:_ComparatorMode_index[i+1]]
}

func (i ComparatorMode) Value() byte {
	return byte(i)
}
