// Code generated by "stringer -type=Direction -output=direction_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirectionDown-0]
	_ = x[DirectionUp-1]
	_ = x[DirectionNorth-2]
	_ = x[DirectionSouth-3]
	_ = x[DirectionWest-4]
	_ = x[DirectionEast-5]
}

const _Direction_name = "DirectionDownDirectionUpDirectionNorthDirectionSouthDirectionWestDirectionEast"

var _Direction_index = [...]uint8{0, 13, 24, 38, 52, 65, 78}

func (i Direction) String() string {
	if i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}

func (i Direction) Value() byte {
	return byte(i)
}
