// Code generated by "stringer -type=DoorHingeSide -output=door_hinge_side_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DoorHingeSideLeft-0]
	_ = x[DoorHingeSideRight-1]
}

const _DoorHingeSide_name = "DoorHingeSideLeftDoorHingeSideRight"

var _DoorHingeSide_index = [...]uint8{0, 17, 35}

func (i DoorHingeSide) String() string {
	if i >= DoorHingeSide(len(_DoorHingeSide_index)-1) {
		return "DoorHingeSide(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DoorHingeSide_name[_DoorHingeSide_index[i]:_DoorHingeSide_index[i+1]]
}

func (i DoorHingeSide) Value() byte {
	return byte(i)
}
