// Code generated by "stringer -type=DoubleBlockHalf -output=double_block_half_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DoubleBlockHalfUpper-0]
	_ = x[DoubleBlockHalfLower-1]
}

const _DoubleBlockHalf_name = "DoubleBlockHalfUpperDoubleBlockHalfLower"

var _DoubleBlockHalf_index = [...]uint8{0, 20, 40}

func (i DoubleBlockHalf) String() string {
	if i >= DoubleBlockHalf(len(_DoubleBlockHalf_index)-1) {
		return "DoubleBlockHalf(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DoubleBlockHalf_name[_DoubleBlockHalf_index[i]:_DoubleBlockHalf_index[i+1]]
}

func (i DoubleBlockHalf) Value() byte {
	return byte(i)
}
