// Code generated by "stringer -type=NoteBlockInstrument -output=note_block_instrument_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoteBlockInstrumentHarp-0]
	_ = x[NoteBlockInstrumentBasedrum-1]
	_ = x[NoteBlockInstrumentSnare-2]
	_ = x[NoteBlockInstrumentHat-3]
	_ = x[NoteBlockInstrumentBass-4]
	_ = x[NoteBlockInstrumentFlute-5]
	_ = x[NoteBlockInstrumentBell-6]
	_ = x[NoteBlockInstrumentGuitar-7]
	_ = x[NoteBlockInstrumentChime-8]
	_ = x[NoteBlockInstrumentXylophone-9]
	_ = x[NoteBlockInstrumentIronXylophone-10]
	_ = x[NoteBlockInstrumentCowBell-11]
	_ = x[NoteBlockInstrumentDidgeridoo-12]
	_ = x[NoteBlockInstrumentBit-13]
	_ = x[NoteBlockInstrumentBanjo-14]
	_ = x[NoteBlockInstrumentPling-15]
}

const _NoteBlockInstrument_name = "NoteBlockInstrumentHarpNoteBlockInstrumentBasedrumNoteBlockInstrumentSnareNoteBlockInstrumentHatNoteBlockInstrumentBassNoteBlockInstrumentFluteNoteBlockInstrumentBellNoteBlockInstrumentGuitarNoteBlockInstrumentChimeNoteBlockInstrumentXylophoneNoteBlockInstrumentIronXylophoneNoteBlockInstrumentCowBellNoteBlockInstrumentDidgeridooNoteBlockInstrumentBitNoteBlockInstrumentBanjoNoteBlockInstrumentPling"

var _NoteBlockInstrument_index = [...]uint16{0, 23, 50, 74, 96, 119, 143, 166, 191, 215, 243, 275, 301, 330, 352, 376, 400}

func (i NoteBlockInstrument) String() string {
	if i >= NoteBlockInstrument(len(_NoteBlockInstrument_index)-1) {
		return "NoteBlockInstrument(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NoteBlockInstrument_name[_NoteBlockInstrument_index[i]:_NoteBlockInstrument_index[i+1]]
}

func (i NoteBlockInstrument) Value() byte {
	return byte(i)
}
