// Code generated by "stringer -type=RailShape -output=rail_shape_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RailShapeNorthSouth-0]
	_ = x[RailShapeEastWest-1]
	_ = x[RailShapeAscendingEast-2]
	_ = x[RailShapeAscendingWest-3]
	_ = x[RailShapeAscendingNorth-4]
	_ = x[RailShapeAscendingSouth-5]
	_ = x[RailShapeSouthEast-6]
	_ = x[RailShapeSouthWest-7]
	_ = x[RailShapeNorthWest-8]
	_ = x[RailShapeNorthEast-9]
}

const _RailShape_name = "RailShapeNorthSouthRailShapeEastWestRailShapeAscendingEastRailShapeAscendingWestRailShapeAscendingNorthRailShapeAscendingSouthRailShapeSouthEastRailShapeSouthWestRailShapeNorthWestRailShapeNorthEast"

var _RailShape_index = [...]uint8{0, 19, 36, 58, 80, 103, 126, 144, 162, 180, 198}

func (i RailShape) String() string {
	if i >= RailShape(len(_RailShape_index)-1) {
		return "RailShape(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RailShape_name[_RailShape_index[i]:_RailShape_index[i+1]]
}

func (i RailShape) Value() byte {
	return byte(i)
}
