// Code generated by "stringer -type=RedstoneSide -output=redstone_side_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RedstoneSideUp-0]
	_ = x[RedstoneSideSide-1]
	_ = x[RedstoneSideNone-2]
}

const _RedstoneSide_name = "RedstoneSideUpRedstoneSideSideRedstoneSideNone"

var _RedstoneSide_index = [...]uint8{0, 14, 30, 46}

func (i RedstoneSide) String() string {
	if i >= RedstoneSide(len(_RedstoneSide_index)-1) {
		return "RedstoneSide(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RedstoneSide_name[_RedstoneSide_index[i]:_RedstoneSide_index[i+1]]
}

func (i RedstoneSide) Value() byte {
	return byte(i)
}
