// Code generated by "stringer -type=SculkSensorPhase -output=sculk_sensor_phase_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SculkSensorPhaseInactive-0]
	_ = x[SculkSensorPhaseActive-1]
	_ = x[SculkSensorPhaseCooldown-2]
}

const _SculkSensorPhase_name = "SculkSensorPhaseInactiveSculkSensorPhaseActiveSculkSensorPhaseCooldown"

var _SculkSensorPhase_index = [...]uint8{0, 24, 46, 70}

func (i SculkSensorPhase) String() string {
	if i >= SculkSensorPhase(len(_SculkSensorPhase_index)-1) {
		return "SculkSensorPhase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SculkSensorPhase_name[_SculkSensorPhase_index[i]:_SculkSensorPhase_index[i+1]]
}

func (i SculkSensorPhase) Value() byte {
	return byte(i)
}
