// Code generated by "stringer -type=SlabType -output=slab_type_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SlabTypeTop-0]
	_ = x[SlabTypeBottom-1]
	_ = x[SlabTypeDouble-2]
}

const _SlabType_name = "SlabTypeTopSlabTypeBottomSlabTypeDouble"

var _SlabType_index = [...]uint8{0, 11, 25, 39}

func (i SlabType) String() string {
	if i >= SlabType(len(_SlabType_index)-1) {
		return "SlabType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SlabType_name[_SlabType_index[i]:_SlabType_index[i+1]]
}

func (i SlabType) Value() byte {
	return byte(i)
}
