// Code generated by "stringer -type=StructureMode -output=structure_mode_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StructureModeSave-0]
	_ = x[StructureModeLoad-1]
	_ = x[StructureModeCorner-2]
	_ = x[StructureModeData-3]
}

const _StructureMode_name = "StructureModeSaveStructureModeLoadStructureModeCornerStructureModeData"

var _StructureMode_index = [...]uint8{0, 17, 34, 53, 70}

func (i StructureMode) String() string {
	if i >= StructureMode(len(_StructureMode_index)-1) {
		return "StructureMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StructureMode_name[_StructureMode_index[i]:_StructureMode_index[i+1]]
}

func (i StructureMode) Value() byte {
	return byte(i)
}
