// Code generated by "stringer -type=Tilt -output=tilt_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TiltNone-0]
	_ = x[TiltUnstable-1]
	_ = x[TiltPartial-2]
	_ = x[TiltFull-3]
}

const _Tilt_name = "TiltNoneTiltUnstableTiltPartialTiltFull"

var _Tilt_index = [...]uint8{0, 8, 20, 31, 39}

func (i Tilt) String() string {
	if i >= Tilt(len(_Tilt_index)-1) {
		return "Tilt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tilt_name[_Tilt_index[i]:_Tilt_index[i+1]]
}

func (i Tilt) Value() byte {
	return byte(i)
}
