// Code generated by "stringer -type=WallSide -output=wall_side_string.go"; DO NOT EDIT.

package states

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WallSideNone-0]
	_ = x[WallSideLow-1]
	_ = x[WallSideTall-2]
}

const _WallSide_name = "WallSideNoneWallSideLowWallSideTall"

var _WallSide_index = [...]uint8{0, 12, 23, 35}

func (i WallSide) String() string {
	if i >= WallSide(len(_WallSide_index)-1) {
		return "WallSide(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WallSide_name[_WallSide_index[i]:_WallSide_index[i+1]]
}

func (i WallSide) Value() byte {
	return byte(i)
}
