// Code generated by generator/properties/main.go; DO NOT EDIT.
package states

type PropertiesEnum interface {
    String() string
}


type AttachFace byte

//go:generate stringer -type=AttachFace -output=attachface_string.go
const (
    AttachFaceFloor AttachFace = iota
    AttachFaceWall
    AttachFaceCeiling
)

type BambooLeaves byte

//go:generate stringer -type=BambooLeaves -output=bambooleaves_string.go
const (
    BambooLeavesNone BambooLeaves = iota
    BambooLeavesSmall
    BambooLeavesLarge
)

type BedPart byte

//go:generate stringer -type=BedPart -output=bedpart_string.go
const (
    BedPartHead BedPart = iota
    BedPartFoot
)

type BellAttachType byte

//go:generate stringer -type=BellAttachType -output=bellattachtype_string.go
const (
    BellAttachTypeFloor BellAttachType = iota
    BellAttachTypeCeiling
    BellAttachTypeSingleWall
    BellAttachTypeDoubleWall
)

type ChestType byte

//go:generate stringer -type=ChestType -output=chesttype_string.go
const (
    ChestTypeSingle ChestType = iota
    ChestTypeLeft
    ChestTypeRight
)

type ComparatorMode byte

//go:generate stringer -type=ComparatorMode -output=comparatormode_string.go
const (
    ComparatorModeCompare ComparatorMode = iota
    ComparatorModeSubtract
)

type Direction byte

//go:generate stringer -type=Direction -output=direction_string.go
const (
    DirectionDown Direction = iota
    DirectionUp
    DirectionNorth
    DirectionSouth
    DirectionWest
    DirectionEast
)

type Axis byte

//go:generate stringer -type=Axis -output=axis_string.go
const (
    X Axis = iota
    Y
    Z
)

type DoorHingeSide byte

//go:generate stringer -type=DoorHingeSide -output=doorhingeside_string.go
const (
    DoorHingeSideLeft DoorHingeSide = iota
    DoorHingeSideRight
)

type DoubleBlockHalf byte

//go:generate stringer -type=DoubleBlockHalf -output=doubleblockhalf_string.go
const (
    DoubleBlockHalfUpper DoubleBlockHalf = iota
    DoubleBlockHalfLower
)

type DripstoneThickness byte

//go:generate stringer -type=DripstoneThickness -output=dripstonethickness_string.go
const (
    DripstoneThicknessTipMerge DripstoneThickness = iota
    DripstoneThicknessTip
    DripstoneThicknessFrustum
    DripstoneThicknessMiddle
    DripstoneThicknessBase
)

type Half byte

//go:generate stringer -type=Half -output=half_string.go
const (
    Top Half = iota
    Bottom
)

type NoteBlockInstrument byte

//go:generate stringer -type=NoteBlockInstrument -output=noteblockinstrument_string.go
const (
    NoteBlockInstrumentHarp NoteBlockInstrument = iota
    NoteBlockInstrumentBasedrum
    NoteBlockInstrumentSnare
    NoteBlockInstrumentHat
    NoteBlockInstrumentBass
    NoteBlockInstrumentFlute
    NoteBlockInstrumentBell
    NoteBlockInstrumentGuitar
    NoteBlockInstrumentChime
    NoteBlockInstrumentXylophone
    NoteBlockInstrumentIronXylophone
    NoteBlockInstrumentCowBell
    NoteBlockInstrumentDidgeridoo
    NoteBlockInstrumentBit
    NoteBlockInstrumentBanjo
    NoteBlockInstrumentPling
)

type PistonType byte

//go:generate stringer -type=PistonType -output=pistontype_string.go
const (
    PistonTypeNormal PistonType = iota
    PistonTypeSticky
)

type RailShape byte

//go:generate stringer -type=RailShape -output=railshape_string.go
const (
    RailShapeNorthSouth RailShape = iota
    RailShapeEastWest
    RailShapeAscendingEast
    RailShapeAscendingWest
    RailShapeAscendingNorth
    RailShapeAscendingSouth
    RailShapeSouthEast
    RailShapeSouthWest
    RailShapeNorthWest
    RailShapeNorthEast
)

type RedstoneSide byte

//go:generate stringer -type=RedstoneSide -output=redstoneside_string.go
const (
    RedstoneSideUp RedstoneSide = iota
    RedstoneSideSide
    RedstoneSideNone
)

type SculkSensorPhase byte

//go:generate stringer -type=SculkSensorPhase -output=sculksensorphase_string.go
const (
    SculkSensorPhaseInactive SculkSensorPhase = iota
    SculkSensorPhaseActive
    SculkSensorPhaseCooldown
)

type SlabType byte

//go:generate stringer -type=SlabType -output=slabtype_string.go
const (
    SlabTypeTop SlabType = iota
    SlabTypeBottom
    SlabTypeDouble
)

type StairsShape byte

//go:generate stringer -type=StairsShape -output=stairsshape_string.go
const (
    StairsShapeStraight StairsShape = iota
    StairsShapeInnerLeft
    StairsShapeInnerRight
    StairsShapeOuterLeft
    StairsShapeOuterRight
)

type StructureMode byte

//go:generate stringer -type=StructureMode -output=structuremode_string.go
const (
    StructureModeSave StructureMode = iota
    StructureModeLoad
    StructureModeCorner
    StructureModeData
)

type Tilt byte

//go:generate stringer -type=Tilt -output=tilt_string.go
const (
    TiltNone Tilt = iota
    TiltUnstable
    TiltPartial
    TiltFull
)

type WallSide byte

//go:generate stringer -type=WallSide -output=wallside_string.go
const (
    WallSideNone WallSide = iota
    WallSideLow
    WallSideTall
)

type FrontAndTop byte

//go:generate stringer -type=FrontAndTop -output=frontandtop_string.go
const (
    DownEast FrontAndTop = iota
    DownNorth
    DownSouth
    DownWest
    UpEast
    UpNorth
    UpSouth
    UpWest
    WestUp
    EastUp
    NorthUp
    SouthUp
)
