// Code generated by data/registry/generate.go; DO NOT EDIT.
package blockentitytype

type BlockEntityType int

func (n BlockEntityType) String() string {
	if n < 0 || int(n) >= len(names) {
		return "<invalid BlockEntityType>"
	}
	return names[n]
}

const (
	Furnace BlockEntityType = iota
	Chest
	TrappedChest
	EnderChest
	Jukebox
	Dispenser
	Dropper
	Sign
	HangingSign
	MobSpawner
	Piston
	BrewingStand
	EnchantingTable
	EndPortal
	Beacon
	Skull
	DaylightDetector
	Hopper
	Comparator
	Banner
	StructureBlock
	EndGateway
	CommandBlock
	ShulkerBox
	Bed
	Conduit
	Barrel
	Smoker
	BlastFurnace
	Lectern
	Bell
	Jigsaw
	Campfire
	Beehive
	SculkSensor
	SculkCatalyst
	SculkShrieker
	ChiseledBookshelf
	SuspiciousSand
	DecoratedPot
)

var names = []string{
	"minecraft:furnace",
	"minecraft:chest",
	"minecraft:trapped_chest",
	"minecraft:ender_chest",
	"minecraft:jukebox",
	"minecraft:dispenser",
	"minecraft:dropper",
	"minecraft:sign",
	"minecraft:hanging_sign",
	"minecraft:mob_spawner",
	"minecraft:piston",
	"minecraft:brewing_stand",
	"minecraft:enchanting_table",
	"minecraft:end_portal",
	"minecraft:beacon",
	"minecraft:skull",
	"minecraft:daylight_detector",
	"minecraft:hopper",
	"minecraft:comparator",
	"minecraft:banner",
	"minecraft:structure_block",
	"minecraft:end_gateway",
	"minecraft:command_block",
	"minecraft:shulker_box",
	"minecraft:bed",
	"minecraft:conduit",
	"minecraft:barrel",
	"minecraft:smoker",
	"minecraft:blast_furnace",
	"minecraft:lectern",
	"minecraft:bell",
	"minecraft:jigsaw",
	"minecraft:campfire",
	"minecraft:beehive",
	"minecraft:sculk_sensor",
	"minecraft:sculk_catalyst",
	"minecraft:sculk_shrieker",
	"minecraft:chiseled_bookshelf",
	"minecraft:suspicious_sand",
	"minecraft:decorated_pot",
}
