// Code generated by generator/blocks/main.go; DO NOT EDIT.
package block

var (
	SnowyProperty = NewPropertyBoolean("snowy")

	StageProperty = NewPropertyInteger("stage", 0, 1)

	Age4Property = NewPropertyInteger("age", 0, 4)

	HangingProperty = NewPropertyBoolean("hanging")

	WaterloggedProperty = NewPropertyBoolean("waterlogged")

	LevelProperty = NewPropertyInteger("level", 0, 15)

	DistanceProperty = NewPropertyInteger("distance", 1, 7)

	PersistentProperty = NewPropertyBoolean("persistent")

	TriggeredProperty = NewPropertyBoolean("triggered")

	NoteProperty = NewPropertyInteger("note", 0, 24)

	PoweredProperty = NewPropertyBoolean("powered")

	OccupiedProperty = NewPropertyBoolean("occupied")

	ExtendedProperty = NewPropertyBoolean("extended")

	ShortProperty = NewPropertyBoolean("short")

	UnstableProperty = NewPropertyBoolean("unstable")

	Age15Property = NewPropertyInteger("age", 0, 15)

	EastProperty = NewPropertyBoolean("east")

	NorthProperty = NewPropertyBoolean("north")

	SouthProperty = NewPropertyBoolean("south")

	UpProperty = NewPropertyBoolean("up")

	WestProperty = NewPropertyBoolean("west")

	PowerProperty = NewPropertyInteger("power", 0, 15)

	Age7Property = NewPropertyInteger("age", 0, 7)

	MoistureProperty = NewPropertyInteger("moisture", 0, 7)

	LitProperty = NewPropertyBoolean("lit")

	RotationProperty = NewPropertyInteger("rotation", 0, 15)

	OpenProperty = NewPropertyBoolean("open")

	LayersProperty = NewPropertyInteger("layers", 1, 8)

	HasRecordProperty = NewPropertyBoolean("has_record")

	BitesProperty = NewPropertyInteger("bites", 0, 6)

	DelayProperty = NewPropertyInteger("delay", 1, 4)

	LockedProperty = NewPropertyBoolean("locked")

	DownProperty = NewPropertyBoolean("down")

	InWallProperty = NewPropertyBoolean("in_wall")

	Age3Property = NewPropertyInteger("age", 0, 3)

	HasBottle0Property = NewPropertyBoolean("has_bottle_0")

	HasBottle1Property = NewPropertyBoolean("has_bottle_1")

	HasBottle2Property = NewPropertyBoolean("has_bottle_2")

	EyeProperty = NewPropertyBoolean("eye")

	Age2Property = NewPropertyInteger("age", 0, 2)

	AttachedProperty = NewPropertyBoolean("attached")

	DisarmedProperty = NewPropertyBoolean("disarmed")

	ConditionalProperty = NewPropertyBoolean("conditional")

	InvertedProperty = NewPropertyBoolean("inverted")

	EnabledProperty = NewPropertyBoolean("enabled")

	Age5Property = NewPropertyInteger("age", 0, 5)

	Age25Property = NewPropertyInteger("age", 0, 25)

	EggsProperty = NewPropertyInteger("eggs", 1, 4)

	HatchProperty = NewPropertyInteger("hatch", 0, 2)

	PicklesProperty = NewPropertyInteger("pickles", 1, 4)

	Age1Property = NewPropertyInteger("age", 0, 1)

	DragProperty = NewPropertyBoolean("drag")

	BottomProperty = NewPropertyBoolean("bottom")

	HasBookProperty = NewPropertyBoolean("has_book")

	SignalFireProperty = NewPropertyBoolean("signal_fire")

	HoneyLevelProperty = NewPropertyInteger("honey_level", 0, 5)

	ChargesProperty = NewPropertyInteger("charges", 0, 4)

	CandlesProperty = NewPropertyInteger("candles", 1, 4)

	BloomProperty = NewPropertyBoolean("bloom")

	CanSummonProperty = NewPropertyBoolean("can_summon")

	ShriekingProperty = NewPropertyBoolean("shrieking")

	BerriesProperty = NewPropertyBoolean("berries")
)
