// Code generated by gen_effects.go DO NOT EDIT.
// Package effects stores information about potion effects in Minecraft.
package effects

// ID describes the numeric ID of an effect.
type ID uint32

// Item describes information about a type of item.
type Effect struct {
	ID          ID
	DisplayName string
	Name        string
	Type        string
}

var (
	Speed = Effect{
		ID:          1,
		DisplayName: "Speed",
		Name:        "Speed",
		Type:        "good",
	}
	Slowness = Effect{
		ID:          2,
		DisplayName: "Slowness",
		Name:        "Slowness",
		Type:        "bad",
	}
	Haste = Effect{
		ID:          3,
		DisplayName: "Haste",
		Name:        "Haste",
		Type:        "good",
	}
	MiningFatigue = Effect{
		ID:          4,
		DisplayName: "Mining Fatigue",
		Name:        "MiningFatigue",
		Type:        "bad",
	}
	Strength = Effect{
		ID:          5,
		DisplayName: "Strength",
		Name:        "Strength",
		Type:        "good",
	}
	InstantHealth = Effect{
		ID:          6,
		DisplayName: "Instant Health",
		Name:        "InstantHealth",
		Type:        "good",
	}
	InstantDamage = Effect{
		ID:          7,
		DisplayName: "Instant Damage",
		Name:        "InstantDamage",
		Type:        "bad",
	}
	JumpBoost = Effect{
		ID:          8,
		DisplayName: "Jump Boost",
		Name:        "JumpBoost",
		Type:        "good",
	}
	Nausea = Effect{
		ID:          9,
		DisplayName: "Nausea",
		Name:        "Nausea",
		Type:        "bad",
	}
	Regeneration = Effect{
		ID:          10,
		DisplayName: "Regeneration",
		Name:        "Regeneration",
		Type:        "good",
	}
	Resistance = Effect{
		ID:          11,
		DisplayName: "Resistance",
		Name:        "Resistance",
		Type:        "good",
	}
	FireResistance = Effect{
		ID:          12,
		DisplayName: "Fire Resistance",
		Name:        "FireResistance",
		Type:        "good",
	}
	WaterBreathing = Effect{
		ID:          13,
		DisplayName: "Water Breathing",
		Name:        "WaterBreathing",
		Type:        "good",
	}
	Invisibility = Effect{
		ID:          14,
		DisplayName: "Invisibility",
		Name:        "Invisibility",
		Type:        "good",
	}
	Blindness = Effect{
		ID:          15,
		DisplayName: "Blindness",
		Name:        "Blindness",
		Type:        "bad",
	}
	NightVision = Effect{
		ID:          16,
		DisplayName: "Night Vision",
		Name:        "NightVision",
		Type:        "good",
	}
	Hunger = Effect{
		ID:          17,
		DisplayName: "Hunger",
		Name:        "Hunger",
		Type:        "bad",
	}
	Weakness = Effect{
		ID:          18,
		DisplayName: "Weakness",
		Name:        "Weakness",
		Type:        "bad",
	}
	Poison = Effect{
		ID:          19,
		DisplayName: "Poison",
		Name:        "Poison",
		Type:        "bad",
	}
	Wither = Effect{
		ID:          20,
		DisplayName: "Wither",
		Name:        "Wither",
		Type:        "bad",
	}
	HealthBoost = Effect{
		ID:          21,
		DisplayName: "Health Boost",
		Name:        "HealthBoost",
		Type:        "good",
	}
	Absorption = Effect{
		ID:          22,
		DisplayName: "Absorption",
		Name:        "Absorption",
		Type:        "good",
	}
	Saturation = Effect{
		ID:          23,
		DisplayName: "Saturation",
		Name:        "Saturation",
		Type:        "good",
	}
	Glowing = Effect{
		ID:          24,
		DisplayName: "Glowing",
		Name:        "Glowing",
		Type:        "bad",
	}
	Levitation = Effect{
		ID:          25,
		DisplayName: "Levitation",
		Name:        "Levitation",
		Type:        "bad",
	}
	Luck = Effect{
		ID:          26,
		DisplayName: "Luck",
		Name:        "Luck",
		Type:        "good",
	}
	BadLuck = Effect{
		ID:          27,
		DisplayName: "Bad Luck",
		Name:        "BadLuck",
		Type:        "bad",
	}
	SlowFalling = Effect{
		ID:          28,
		DisplayName: "Slow Falling",
		Name:        "SlowFalling",
		Type:        "good",
	}
	ConduitPower = Effect{
		ID:          29,
		DisplayName: "Conduit Power",
		Name:        "ConduitPower",
		Type:        "good",
	}
	DolphinsGrace = Effect{
		ID:          30,
		DisplayName: "Dolphin's Grace",
		Name:        "DolphinsGrace",
		Type:        "good",
	}
	BadOmen = Effect{
		ID:          31,
		DisplayName: "Bad Omen",
		Name:        "BadOmen",
		Type:        "bad",
	}
	HeroOfTheVillage = Effect{
		ID:          32,
		DisplayName: "Hero of the Village",
		Name:        "HeroOfTheVillage",
		Type:        "good",
	}
	Darkness = Effect{
		ID:          33,
		DisplayName: "Darkness",
		Name:        "Darkness",
		Type:        "bad",
	}
)

// ByID is an index of minecraft items by their ID.
var ByID = map[ID]*Effect{
	1:  &Speed,
	2:  &Slowness,
	3:  &Haste,
	4:  &MiningFatigue,
	5:  &Strength,
	6:  &InstantHealth,
	7:  &InstantDamage,
	8:  &JumpBoost,
	9:  &Nausea,
	10: &Regeneration,
	11: &Resistance,
	12: &FireResistance,
	13: &WaterBreathing,
	14: &Invisibility,
	15: &Blindness,
	16: &NightVision,
	17: &Hunger,
	18: &Weakness,
	19: &Poison,
	20: &Wither,
	21: &HealthBoost,
	22: &Absorption,
	23: &Saturation,
	24: &Glowing,
	25: &Levitation,
	26: &Luck,
	27: &BadLuck,
	28: &SlowFalling,
	29: &ConduitPower,
	30: &DolphinsGrace,
	31: &BadOmen,
	32: &HeroOfTheVillage,
	33: &Darkness,
}

// ByName is an index of minecraft items by their name.
var ByName = map[string]*Effect{
	"Speed":            &Speed,
	"Slowness":         &Slowness,
	"Haste":            &Haste,
	"MiningFatigue":    &MiningFatigue,
	"Strength":         &Strength,
	"InstantHealth":    &InstantHealth,
	"InstantDamage":    &InstantDamage,
	"JumpBoost":        &JumpBoost,
	"Nausea":           &Nausea,
	"Regeneration":     &Regeneration,
	"Resistance":       &Resistance,
	"FireResistance":   &FireResistance,
	"WaterBreathing":   &WaterBreathing,
	"Invisibility":     &Invisibility,
	"Blindness":        &Blindness,
	"NightVision":      &NightVision,
	"Hunger":           &Hunger,
	"Weakness":         &Weakness,
	"Poison":           &Poison,
	"Wither":           &Wither,
	"HealthBoost":      &HealthBoost,
	"Absorption":       &Absorption,
	"Saturation":       &Saturation,
	"Glowing":          &Glowing,
	"Levitation":       &Levitation,
	"Luck":             &Luck,
	"BadLuck":          &BadLuck,
	"SlowFalling":      &SlowFalling,
	"ConduitPower":     &ConduitPower,
	"DolphinsGrace":    &DolphinsGrace,
	"BadOmen":          &BadOmen,
	"HeroOfTheVillage": &HeroOfTheVillage,
	"Darkness":         &Darkness,
}
